=== 52North/worldviz/data/xsd/DatasetDescription.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
XML Schema Definition (XSD) for meta-datasets to be used in the context of the WorldViz project. 
Authors: Benno Schmidt, Christian Danowski, Department of Geodesy, Bochum University of Applied Sciences.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="DatasetDescription">
		<xs:annotation>
			<xs:documentation>
			This file holds additional meta-information that is not part of the actual data file. 
			Especially meta-data which document the underlying data-source is given.
      </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SpatialScaleHint" type="SpatialScaleHintType">
					<xs:annotation>
						<xs:documentation>
						In the WorldViz context, most often this scale-hint will be 'World-wide'.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="CovereredTime">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="1" minOccurs="0" name="TimePeriod">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="begin" type="xs:date"/>
										<xs:element name="end" type="xs:date"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="DatasetReference" type="xs:string"/>
				<xs:element name="SourceFileReference">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="format" type="xs:string"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Source">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ContactPersons" type="xs:string"/>
							<xs:element name="URI">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="accessDate" type="xs:string"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="AlternativeURIs">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="URI" type="xs:string">
											<xs:annotation>
												<xs:documentation>Here additional URLs can be documented.</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element maxOccurs="1" minOccurs="0" name="Notes" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CopyrightInformation" type="xs:string"/>
				<xs:element name="ImportProcess">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="1" name="Description" type="Description"/>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="QualityCheck" type="QualityCheck"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:float"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Description">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="languageCode"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="languageCode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EN"/>
			<xs:enumeration value="DE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="QualityCheck">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="date" type="xs:string"/>
				<xs:attribute name="responsiblePerson" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="SpatialScaleHintType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="World-wide"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== 52North/worldviz/data/earth/IndiaTreeCover2013_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This document holds additional meta-information that is not part of an actual shape file to be processed 
in the context of the BO's ENE project. 
Author: Christian Danowski, Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>India</SpatialScaleHint>
	<CovereredTime/>
	<DatasetReference>IndiaTreeCover2013.xml</DatasetReference><!-- Dateiname-->
	<SourceFileReference/>
	<Source>
		<ContactPersons>Dr. Ashok A. Sonkusare</ContactPersons><!-- Kontaktpersonen betreffend der abgegriffenen Informationen-->
		<URI accessDate="2015-10-20 +12:00">https://data.gov.in/catalog/stateut-wise-tree-cover-estimates</URI><!-- Datum des Zugriffes sowie deren Quelle-->
		<AlternativeURIs><!--The follwing URI links to the website where the direct download link from above is from.-->
			<URI>https://data.gov.in/node/123108/datastore/export/csv</URI><!--The following URI represents the direkt download link to the shape file-->
		</AlternativeURIs>
		<Notes>Bie diesem Datensatz handelt es sich um die mit Bäumen bedeckte Fläche der indischen States.</Notes>
	</Source>
	<CopyrightInformation>Dr. Ashok A. Sonkusare - https://data.gov.in/</CopyrightInformation><!-- Copyright Informationen-->
	<ImportProcess>
		<Description language="DE"><!-- Erklaerung der Arbeitsabfolge-->
	   		Die Datei kann direkt in verschiedenen Formaten (hier CSV) heruntergeladen werden. 
			Anschließend muss die Datei umbenannt werden (hier: India_TreeCover2013.csv).
			
			Die in der CSV-Datei enthaltenen Parameter konnten mittels eines eigens entwickelten Java-Programms in den 'Entry'-Abschnitt der "IndiaTreeCover2013.xml"-Datei überführt werden.	   		
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/NuclearPowerPlants_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint>
	<CovereredTime>
		<TimePeriod>
			<begin>2014-01-01+01:00</begin>
			<end>2014-01-01+01:00</end>
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>NuclearPowerPlants.xml</DatasetReference>
	<SourceFileReference format="KML">sourceFiles/AKW_Standorte.kml</SourceFileReference>
	<Source>
		<ContactPersons/>
		<URI accessDate="2014-04-28 +15:00">http://en.wikipedia.org/wiki/List_of_nuclear_power_stations</URI><!-- Datum der Datenbeschaffung sowie dessen Quelle -->
		<AlternativeURIs>
			<URI/>
		</AlternativeURIs>
		<Notes/>
	</Source>
	<CopyrightInformation>Wikipedia http://en.wikipedia.org/wiki/Wikipedia:Copyrights</CopyrightInformation><!-- Copyright Informationen-->
	<ImportProcess>
		<Description language="DE"><!-- Dokumentation betreffend der Abfolge der Arbeitsschritte-->
		Download einer KML mit Namen und Koordinaten über 
		http://toolserver.org/~para/cgi-bin/kmlexport?project=en.wikipedia.org&amp;article=List_of_nuclear_power_stations
		Kopieren der Tabellen von der oben angegeben Wikipediaseite in eine CSV-Tabelle. ID hinzufügen.
		Öffnen der KML in QGIS und speichern der angezeigten Layer als Shape. Shapedateien zusammenführen. (Vektor-Datenbankmanagment-...)
		Shapedatei und CSV in QGIS öffnen. Der Shapedatei mit dem Feldrechner eine ID über $rowindex hinzufügen.
		Shapedatei-Eigenschaften-Verknüpfungen-Join durchführen.
		Speichern der verknüpften Shape und export als KML.
		Überführung der KML in das XML-Schema.
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/ElectricityProductionFromSpecificRessource_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
Author: Matthias Schmiedel, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint>
	<CovereredTime>
		<TimePeriod>
			<begin>2008-01-01+01:00</begin><!-- Daten beziehen sich auf das Jahr 2008-->
			<end> 2008-01-01+01:00</end>
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>ElectricityProductionFromSpecificRessource.xml</DatasetReference><!-- Dateiname des Datensatzes der Erzeugung von Elektrezietät-->
	<SourceFileReference format="XLSX">sourceFiles/ElectricityProductionFromSpecificRessource.xlsx</SourceFileReference>
	<Source>
		<ContactPersons/>
		<URI accessDate="2014-05-14 +11:00">http://www.iea.org/statistics/statisticssearch/report/?country=GERMANY&amp;product=electricityandheat&amp;year=2008</URI>
		<AlternativeURIs><!-- Here additional URLs can be documented. -->
			<URI/>
		</AlternativeURIs>
		<Notes/>
	</Source>
	<CopyrightInformation>unknown</CopyrightInformation>
	<ImportProcess>
		<Description language="DE">
		Nachfolgende Änderung bzw. Ergänzung der Einzelnen Spalten um den Identifikator der Länderkürzel anhand der  ISO 3166 Alpha-2 
		zu finden unter: http://de.wikipedia.org/wiki/ISO-3166-1-Kodierliste
		Die nun erarbeiteten Daten, müssen nun in eine .csv Datei umgewandelt werden, welche durch den Identifier des Ländercodes zugeordnet werden können um in die XML Struktur
		überführt zu werden
	   	</Description>
		<QualityCheck date="09.06.2014 +22:00" responsiblePerson="Matthias Schmiedel">
	   		Ergänzung des Metadatensatzes bezüglich der Herstellung von Elektrizität.
	   	</QualityCheck>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/Flows_of_trade_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
WorldViz meta-information file.
Note: This file holds additional meta-information that is not part of an actual data file to be processed in the context of WorldViz project. 
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint>
	<CovereredTime>
		<TimePeriod>
			<begin>2004-01-01</begin>
			<end>2004-12-31</end>
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>Flows_of_trade.xml</DatasetReference>
	<SourceFileReference/>
	<Source>
		<ContactPersons/>
		<URI>http://www.tandem-verlag.de/product_info.php/info/p1125_abitur-clever-vorbereitet---geografie.html</URI>
		<AlternativeURIs/>
		<Notes/>
	</Source>
	<CopyrightInformation>Dr. Peter Guettler, Berlin</CopyrightInformation>
	<ImportProcess>
		<Description language="DE">
 	   		Erstellung der Pajek-Beschreibung direkt aus aus der Grafik aus dem Buch "Geografie : Abitur clever vorbereitet", tandem-Verlag.
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/FossilResources_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
Author: Artur Grzesiuk, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint>
	<CovereredTime>
		<TimePeriod>
			<begin>2012-01-01+01:00</begin><!-- Daten beziehen sich auf das Jahr 2012-->
			<end> 2012-01-01+01:00</end>
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>FossilResources.xml</DatasetReference><!-- Dateiname des Datensatzes der Fossilen Ressourcen-->
	<SourceFileReference format="CSV">FossilRessources.csv</SourceFileReference>
	<Source>
		<ContactPersons/>
		<URI accessDate="2014-04-12 +11:00">http://www.bgr.bund.de/energiestudie2013</URI>
		<AlternativeURIs><!-- Here additional URLs can be documented. -->
			<URI/>
		</AlternativeURIs>
		<Notes/>
	</Source>
	<CopyrightInformation>unknown</CopyrightInformation>
	<ImportProcess>
		<Description language="DE">
		Download der Daten als Excel (.xlsx) Format ueber http://www.bgr.bund.de/energiestudie2013.
		Nachfolgende aenderung bzw. Ergaenzung der Einzelnen Spalten um den Identifikator der Laenderkuerzel anhand der  ISO 3166 Alpha-2 
		zu finden unter: http://de.wikipedia.org/wiki/ISO-3166-1-Kodierliste
		Die nun erarbeiteten Daten, muessen nun in eine .csv Datei umgewandelt werden, welche durch den Identifier des Laendercodes zugeordnet werden koennen um in die XML Struktur
		ueberfuehrt zu werden
	   	</Description>
		<QualityCheck date="04.05.2014 +22:00" responsiblePerson="Artur Grzesiuk">
	   		Ergaenzung des Metadatensatzes bezueglich der Fossilen Rohstoffe
	   	</QualityCheck>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/IndiaStates_withoutTelangana_simplifiedBorders_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This document holds additional meta-information that is not part of an actual shape file to be processed 
in the context of the BO's ENE project. 
Author: Christian Danowski, Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>India</SpatialScaleHint>
	<CovereredTime/>
	<DatasetReference>IndiaStates_withoutTelangana_simplifiedBorders.xml</DatasetReference><!-- Dateiname-->
	<SourceFileReference/>
	<Source>
		<ContactPersons>Devdatta Tengshe</ContactPersons><!-- Kontaktpersonen betreffend der abgegriffenen Informationen-->
		<URI accessDate="2015-10-20 +12:00">https://github.com/datameet/maps/tree/master/States</URI><!-- Datum des Zugriffes sowie deren Quelle-->
		<AlternativeURIs><!--The follwing URI links to the website where the direct download link from above is from.-->
			<URI>https://github.com/datameet/maps</URI><!--The following URI represents the direkt download link to the shape file-->
		</AlternativeURIs>
		<Notes>Bie diesem Datensatz handelt es sich um vereinfachte State-Grenzen (mit deutschen Bundesländern zu vergleichen) Indiens ohne den neu gegründeten State Telangana.</Notes>
	</Source>
	<CopyrightInformation>Devdatta Tengshe</CopyrightInformation><!-- Copyright Informationen-->
	<ImportProcess>
		<Description language="DE"><!-- Erklaerung der Arbeitsabfolge-->
	   		Die Shape-Datei kann direkt zusammen mit den ergaenzenden DBF-, PRJ- sowie SHX-Dateien heruntergeladen werden. 
			Anschließend wurde die Schreibweise einiger indischen States manuell korrigiert 
			und der Spaltenname für die Bezeichner der States wurde zu "NAME" geändert (per QGIS die Attribut-Tabelle bearbeitet.)
			Zusätzlich wurden hierbei noch die States Telangana und Andhra Pradesh zusammengefasst (als Andhra Pradesh).
			Weiterhin wurden mittels QGIS die State-Grenzen vereinfacht.
	   		
	   		Hinweis: Die DBF-Datei wurde zusaetzlich mit Hilfe von Microsoft Excel in eine aequivalente CSV-Datei umgewandelt, um den Datensatz "IndiaStateNames_withoutTelangana.xml" zu erzeugen. 
			Siehe auch "IndiaStateNames_withoutTelangana_meta.xml".
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/IndiaTreeCover2011_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This document holds additional meta-information that is not part of an actual shape file to be processed 
in the context of the BO's ENE project. 
Author: Christian Danowski, Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>India</SpatialScaleHint>
	<CovereredTime/>
	<DatasetReference>IndiaTreeCover2011.xml</DatasetReference><!-- Dateiname-->
	<SourceFileReference/>
	<Source>
		<ContactPersons>ENVIS Centre, Ministry of Environment and Forest, Govt. of India</ContactPersons><!-- Kontaktpersonen betreffend der abgegriffenen Informationen-->
		<URI accessDate="2015-10-27 +12:00">http://www.wwfenvis.nic.in/Database/NationalForestPolicy_4518.aspx?format=Print</URI><!-- Datum des Zugriffes sowie deren Quelle-->
		<AlternativeURIs><!--The follwing URI links to the website where the direct download link from above is from.-->
		</AlternativeURIs>
		<Notes>Bie diesem Datensatz handelt es sich um die mit Bäumen bedeckte Fläche der indischen States.</Notes>
	</Source>
	<CopyrightInformation>ENVIS Centre, Ministry of Environment and Forest, Govt. of India</CopyrightInformation><!-- Copyright Informationen-->
	<ImportProcess>
		<Description language="DE"><!-- Erklaerung der Arbeitsabfolge-->
	   		Die Daten wurden in eine CSV-Datei übertragen (hier: India_TreeCover2011.csv). 
			
			Die in der CSV-Datei enthaltenen Parameter konnten mittels eines eigens entwickelten Java-Programms in den 'Entry'-Abschnitt der "IndiaTreeCover2011.xml"-Datei überführt werden.	   		
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/CarbonEmissions_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This example shows how to hold additional meta-information that is not part of an actual data file to be processed 
in the context of the BO's ENE project. 
Primarly, meta-data which document the underlying data-source should be given
 in such DatasetDescriptions.
Authors: Benno Schmidt, Christian Danowski, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint><!-- 
	For the GI-project "Gespraech mit der Erde", this scale hint always will be "World-wide". In the future, regional data will
	be processed, so that other values might appear. 
	-->
	<CovereredTime>
	<!-- 
	Zeitraum, fuer welchen die Kohlenstoff Emmisionen als Daten vorliegen
	-->
		<TimePeriod>
			<begin>2000-01-01+01:00</begin>
 <!-- Startzeitraum 
-->	
			<end>2010-12-31+01:00</end>
 <!-- Endzeitraum  
-->
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>CarbonEmissions.xml</DatasetReference>
 <!-- Dateiname der xml Datenquelle 
-->
	<SourceFileReference format="CSV">sourceFiles/UNEP-EDE__edgar_co2_total__1396438740.csv</SourceFileReference>
 <!-- Dateiformat der Quelledatei: Hier Daten stammen aus einer csv Datei 
-->
	<Source>
  <!-- Quelle 
-->
		<ContactPersons/>
 <!-- Falls Kontaktpersonen, fuer die Quelldatei, vorhanden sind 
-->
		<URI accessDate="2014-04-12 +11:00">http://geodata.grid.unep.ch/</URI>
  <!-- Datum, andem die Daten abgerufen wurden, mit Link zur Quelle  
-->
		<AlternativeURIs><!-- Here additional URLs can be documented. -->
			<URI/>
		</AlternativeURIs>
		<Notes/>
 <!-- Zusaetzliche Informationen zu den Daten 
-->
	</Source>
	<CopyrightInformation>UNEP - United Nations Environment Programme; European Commission, Joint Research Centre (JRC)/PBL Netherlands Environmental Assessment Agency.</CopyrightInformation>
  <!-- Anzugebene Copyright Informationen 
-->
	<ImportProcess>
		<Description language="DE">
 <!-- Hier werden die noetigen Schritte beschrieben die noetig waren, um aus der Qulldatei die noetigen Informationen zu extrahieren 
-->
	   		Von obiger URL (siehe 'URI'-Tag) wurde der Datensatz 'Emissions of CO2 - Total (Model Estimations, EDGAR v.4.2 FT2010)' als CSV-Datei bezogen. 
			Die ersten vier Zeilen der CSV-Datei enthalten Metadaten wie Titel, Einheit und URL. Diese Zeilen muessen beim Auslesen der Datei geskipped werden. Erst in Zeile fuenf befinden sich die Spaltenueberschriften.
	   		Die CSV-Datei wurde schlie√ülich genutzt, um ueber ein eigens entwickeltes Java-Programm den 'Entries'-Abschnitt der 'CarbonEmissions.xml'-Datei (siehe 'DatasetReference'-Tag) zu erstellen.
	   		Die weiteren Informationen der 'CarbonEmissions.xml'-Datei wurden per Hand eingetragen.
			
			Nachtrag vom 03.06.2014:
	   		Der Datensatz fuer "Antarctic" musste manuell angepasst werden. In der Source-File waren ISO3166-Alpha2 und ISO3166-Alpha3-Codes vertauscht! Daher musste in der XML-Datei der ENE:CountryCode von 'ATA' zu 'AQ' gesetzt werden.
	   	</Description>
		<QualityCheck date="2014-04-13 +11:00" responsiblePerson="Christian Danowski">
 <!-- Datum, andem die Daten auf ihre Qualitaet kontrolliert wurden 
-->
	   		Datensaetze aus generiertem XML-Dokument stichprobenhaft von Hand mit Tabelle im Web verglichen.
	   	</QualityCheck>
	</ImportProcess>
</DatasetDescription>
