=== 52North/worldviz/data/xsd/DatasetDescription.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
XML Schema Definition (XSD) for meta-datasets to be used in the context of the WorldViz project. 
Authors: Benno Schmidt, Christian Danowski, Department of Geodesy, Bochum University of Applied Sciences.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="DatasetDescription">
		<xs:annotation>
			<xs:documentation>
			This file holds additional meta-information that is not part of the actual data file. 
			Especially meta-data which document the underlying data-source is given.
      </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SpatialScaleHint" type="SpatialScaleHintType">
					<xs:annotation>
						<xs:documentation>
						In the WorldViz context, most often this scale-hint will be 'World-wide'.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="CovereredTime">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="1" minOccurs="0" name="TimePeriod">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="begin" type="xs:date"/>
										<xs:element name="end" type="xs:date"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="DatasetReference" type="xs:string"/>
				<xs:element name="SourceFileReference">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="format" type="xs:string"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Source">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ContactPersons" type="xs:string"/>
							<xs:element name="URI">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="accessDate" type="xs:string"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="AlternativeURIs">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="URI" type="xs:string">
											<xs:annotation>
												<xs:documentation>Here additional URLs can be documented.</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element maxOccurs="1" minOccurs="0" name="Notes" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CopyrightInformation" type="xs:string"/>
				<xs:element name="ImportProcess">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="1" name="Description" type="Description"/>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="QualityCheck" type="QualityCheck"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:float"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Description">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="languageCode"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="languageCode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EN"/>
			<xs:enumeration value="DE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="QualityCheck">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="date" type="xs:string"/>
				<xs:attribute name="responsiblePerson" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="SpatialScaleHintType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="World-wide"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== 52North/worldviz/data/earth/Population_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This example shows how to hold additional meta-information that is not part of an actual data file to be processed 
in the context of the BO's ENE project. 
Primarly, meta-data which document the underlying data-source should be given
 in such DatasetDescriptions.
Authors: Benno Schmidt, Christian Danowski, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint><!-- 
	For the GI-project "Gespraech mit der Erde", this scale hint always will be "World-wide". In the future, regional data will
	be processed, so that other values might appear. 
	-->
	<CovereredTime>
		<TimePeriod>
			<begin>2000-01-01+01:00</begin>
			<end>2010-12-31+01:00</end>
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>Population.xml</DatasetReference>
	<SourceFileReference format="CSV">UNEP-EDE__pop_total__1398251955.csv</SourceFileReference>
	<Source>
		<ContactPersons/>
		<URI accessDate="2014-04-23 +11:00">http://geodata.grid.unep.ch/</URI>
		<AlternativeURIs><!-- Here additional URLs can be documented. -->
			<URI/>
		</AlternativeURIs>
		<Notes/>
	</Source>
	<CopyrightInformation>UNEP - United Nations Environment Programme; European Commission, Joint Research Centre (JRC)/PBL Netherlands Environmental Assessment Agency.</CopyrightInformation>
	<ImportProcess>
		<Description language="DE">
	   		Von obiger URL (siehe 'URI'-Tag) wurde der Datensatz 'Population - Total both Sexes' als CSV-Datei bezogen. 
			Die ersten vier Zeilen der CSV-Datei enthalten Metadaten wie Titel, Einheit und URL. Diese Zeilen mueessen beim Auslesen der Datei geskipped werden. Erst in Zeile fueenf befinden sich die Spaltenueeberschriften.
	   		Die CSV-Datei wurde schlie√ülich genutzt, um ueeber ein eigens entwickeltes Java-Programm den 'Entries'-Abschnitt der 'Population.xml'-Datei (siehe 'DatasetReference'-Tag) zu erstellen.
	   		Die weiteren Informationen der 'Population.xml'-Datei wurden per Hand eingetragen.
			
			Nachtrag vom 03.06.2014:
	   		Der Datensatz fueer "Antarctic" musste manuell angepasst werden. In der Source-File waren ISO3166-Alpha2 und ISO3166-Alpha3-Codes vertauscht! Daher musste in der XML-Datei der ENE:CountryCode von 'ATA' zu 'AQ' gesetzt werden.
	   	</Description>
		<QualityCheck date="2014-04-28 +09:00" responsiblePerson="Christian Danowski">
	   		Datensaetze aus generiertem XML-Dokument stichprobenhaft von Hand mit Tabelle im Web verglichen.
	   	</QualityCheck>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/CountriesShape_simplified_50m_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This document holds additional meta-information that is not part of an actual shape file to be processed 
in the context of the BO's ENE project. 
Author: Christian Danowski, Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint>
	<CovereredTime/>
	<DatasetReference>CountriesShape_simplified_50m.xml</DatasetReference><!-- Dateiname-->
	<SourceFileReference/>
	<Source>
		<ContactPersons>Nathaniel Vaughn KELSO</ContactPersons><!-- Kontaktpersonen betreffend der abgegriffenen Informationen-->
		<URI accessDate="2015-01-20 +12:00">http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip</URI><!-- Datum des Zugriffes sowie deren Quelle-->
		<AlternativeURIs><!--The follwing URI links to the website where the direct download link from above is from.-->
			<URI>http://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-countries-2/</URI><!--The following URI represents the direkt download link to the shape file-->
		</AlternativeURIs>
		<Notes>Bie diesem Datensatz handelt es sich um generalisierte De-Facto-Grenzen. Durch die Generalisierung in einem Maßstab von 1:50m sind kleine Inseln/Länder nicht mehr enthalten! 
		Insgesamt sind noch 241 von 255 Ländern abgebildet. (255 Länder beziehen sich auf den Datensatz im Maßstab von 1:10m von www.naturalearthdata.com)</Notes>
	</Source>
	<CopyrightInformation>Nathaniel Vaughn KELSO, Project Manager - http://www.naturalearthdata.com/</CopyrightInformation><!-- Copyright Informationen-->
	<ImportProcess>
		<Description language="DE"><!-- Erklärung der Arbeitsabfolge-->
	   		Die Shape-Datei kann direkt zusammen mit den ergänzenden DBF-, PRJ- sowie SHX-Dateien unter dem Punkt "Admin 0 – Countries" als ZIP-Archiv heruntergeladen werden. 
			Die Option "Download Countries" zeigt auf ein ZIP-Archiv mit den politischen Grenzen der Länder, während die Option "Download without boundary lakes" eventuelle 
			Seetopographien (Trennung von Ländern durch Seegrenzen) beinhaltet.
			Für dieses Projekt wurde die erste Option (de-facto Grenzen) genutzt.
	   		Nach Extraktion in den Ordner "ne_50m_admin_0_countries" stehen alle Dateien unmittelbar zur Verfügung.
	   		
	   		Hinweis: Die DBF-Datei wurde zusätzlich mit Hilfe von Microsoft Excel in eine äquivalente CSV-Datei umgewandelt, um den Datensatz "CountryCodes_simplified_50m.xml" zu erzeugen. 
			Siehe auch "CountryCodes_simplified_50m_meta.xml".
			
			Update(29.04.2015): ISO3166-Einträge von Kosovo und Somaliland geändert. Eigentlich ist bei beiden kein offizielles ISO3166-Kennzeichen existent. 
			Diese werden aber für eine eindeutige Referenzierung benötigt. Daher wurden die Kürzel 'KV' und 'KSV' für Kosovo sowie 'SOL' und 'SOL' für Somaliland benutzt.
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/SeaPlasticWaste_IncorrectlyDisposedWastePerCapita_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This example shows how to hold additional meta-information that is not part of an actual data file to be processed 
in the context of the BO's ENE project. 
Primarly, meta-data which document the underlying data-source should be given
 in such DatasetDescriptions.
Authors: Benno Schmidt, Christian Danowski, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint><!-- 
	For the GI-project "Gespraech mit der Erde", this scale hint always will be "World-wide". In the future, regional data will
	be processed, so that other values might appear. 
	-->
	<CovereredTime>
		<TimePeriod>
			<begin>2010-01-01+01:00</begin>
 <!-- Startzeitraum 
-->	
			<end>2010-12-31+01:00</end>
 <!-- Endzeitraum  
-->
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>SeaPlasticWaste_IncorrectlyDisposedWastePerCapita.xml</DatasetReference>
 <!-- Dateiname der xml Datenquelle 
-->
	<SourceFileReference format=""></SourceFileReference>
 <!-- Dateiformat der Quelledatei: Hier Daten stammen aus einer csv Datei 
-->
	<Source>
  <!-- Quelle 
-->
		<ContactPersons/>
 <!-- Falls Kontaktpersonen, fuer die Quelldatei, vorhanden sind 
-->
		<URI accessDate="2015-09-01 +09:00">http://www.spiegel.de/wissenschaft/mensch/interaktive-weltkarte-wo-der-plastikmuell-herkommt-a-1018215.html</URI>
  <!-- Datum, andem die Daten abgerufen wurden, mit Link zur Quelle  
-->
		<AlternativeURIs><!-- Here additional URLs can be documented. -->
			<URI accessDate="2015-09-01 +09:00">http://www.sciencemag.org/content/347/6223/768</URI>
		</AlternativeURIs>
		<Notes>
		Der Datensatz beschreibt die Menge an Plastikmüll pro Person, die im Jahr 2010 unsachgemäß entsorgt wurde. 
		Es existiert ein Datensatz für jedes Land, welches maximal 50km von einem Meer entfernt ist. Die übrigen Länder sind nicht berücksichtigt.
		</Notes>
 <!-- Zusaetzliche Informationen zu den Daten 
-->
	</Source>
	<CopyrightInformation>Katharina Borchert, Jesper Doub, Ericusspitze 1, 20457 Hamburg; 
	enna R. Jambeck, Roland Geyer, Chris Wilcox, Theodore R. Siegler, Miriam Perryman, Anthony Andrady, Ramani Narayan, Kara Lavender Law</CopyrightInformation>
  <!-- Anzugebene Copyright Informationen 
-->
	<ImportProcess>
		<Description language="DE">
 <!-- Hier werden die noetigen Schritte beschrieben die noetig waren, um aus der Qulldatei die noetigen Informationen zu extrahieren 
-->
	   		Obige SpiegelOnline-URL (siehe 'URI'-Tag) zeigt eine interaktive Weltkarte, die die entsprechenden Werte der Länder per MouseOver-Event anzeigt. 
			Jeder einzelne Wert wurde manuell abgelesen und in die XML-Datei unter 'DatasetReference'-Tag eingetragen.
	   	</Description>
		<QualityCheck date="2015-09-01 +11:00" responsiblePerson="Christian Danowski">
 <!-- Datum, andem die Daten auf ihre Qualitaet kontrolliert wurden 
-->
	   		Datensaetze aus generiertem XML-Dokument stichprobenhaft von Hand mit Tabelle im Web verglichen.
	   	</QualityCheck>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/EarthAtNight_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This example shows how to hold additional meta-information that is not part of an actual data file to be processed 
in the context of the BO's ENE project. 
Primarly, meta-data which document the underlying data-source should be given
 in such DatasetDescriptions.

Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd">
	<SpatialScaleHint>World-wide</SpatialScaleHint>
 <!-- Weltweite abdeckung-->
	<!-- 
	For the GI-project "Gespr채ch mit der Erde", this scale hint always will be "World-wide". In the future, regional data will
	be processed, so that other values might appear. 
	--> 
	<CovereredTime />
	<DatasetReference>EarthAtNight.xml</DatasetReference>
 <!-- Dateiname-->
	<SourceFileReference />
	<Source>
		<ContactPersons />
		<URI accessDate="2014-03-12 +11:00">http://www.nasa.gov/mission_pages/NPP/news/earth-at-night.html</URI>
 <!-- Zeitangabe sowie Quelle der abgegriffenen Daten-->
		<AlternativeURIs />
		<Notes>Images with higher resolution are available on the Web.</Notes>
 <!-- Bemerkungen-->
	</Source>
	<CopyrightInformation>NASA Earth Observatory/NOAA NGDC</CopyrightInformation>
 <!-- Copyright Informationen-->
	<ImportProcess>
		<Description language="DE">
 <!-- Erkl채rung der Arbeitsschritte-->
	   		Das Image l채sst sich problemlos aus dem Web herunterladen. Zu beachten ist, dass die Pixel sich auf das
	   		lon/lat-Koordinatensystem der Erde beziehen m체ssen!
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/CountriesPoint_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This document holds additional meta-information that is not part of an actual shape file to be processed 
in the context of the BO's ENE project. 
Author: Christian Danowski, Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint>
	<CovereredTime/>
	<DatasetReference>CountriesPoint.xml</DatasetReference><!-- Dateiname-->
	<SourceFileReference>sourceFiles/CountriesPoint.xlsx</SourceFileReference>
	<Source>
		<ContactPersons>Bjorn Sandvik</ContactPersons><!-- Kontaktpersonen betreffend der abgegriffenen Informationen-->
		<URI accessDate="2014-03-12 +11:00">http://thematicmapping.org/downloads/world_borders.php</URI><!-- Datum des Zugriffes sowie deren Quelle-->
		<AlternativeURIs><!--The following URI points to the original shape-file that was manipulated by Bjorn Sandvik. Main changes: 
    			For further information please check his website: http://thematicmapping.org/downloads/world_borders.php-->
			<URI>http://www.mappinghacks.com/data/</URI><!--The following URI represents the direkt download link to the shape file-->
			<URI>http://thematicmapping.org/downloads/TM_WORLD_BORDERS-0.3.zip</URI>
		</AlternativeURIs>
		<Notes/>
	</Source>
	<CopyrightInformation>Bjorn Sandvik - thematicmapping.org</CopyrightInformation><!-- Copyright Informationen-->
	<ImportProcess>
		<Description language="DE"><!-- Erklärung der Arbeitsabfolge-->
		Die CountriesPoint.xml wurde aus CoutriesShape erstellt. 
		Dafür wurde die Quelldatei (TM_World_Borders03.shp) in QGIS eingeladen und als CSV (CountriesPoint.csv) exportiert.
		Dadurch erhält man eine CSV, welche die Daten der Shapedatei (Ländercodes, Einwohner,...) und einen
		Landesmittelpunkt enthält. Mit Excel wurde diese CSV geladen und eine XML und KML-Struktur aufgebaut (CountriesPoint.xlsx)
		Ergebnis: CountriesPoint.xml und kml/CountriesPoint.kml
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/HardCoalResources_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This example shows how to hold additional meta-information that is not part of an actual data file to be processed 
in the context of the BO's ENE project. 
Primarly, meta-data which document the underlying data-source should be given in such DatasetDescriptions.
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
Letzte aenderung: 02. Juni 2014 von Artur Grzesiuk
-->
<DatasetDescription version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd">
	<SpatialScaleHint>World-wide</SpatialScaleHint>
	<!-- 
	For the GI-project "Gespraech mit der Erde", this scale hint always will be "World-wide". In the future, regional data will
	be processed, so that other values might appear. 
	--> 
	<CovereredTime>
		<TimePeriod>
			<begin>2012-01-01+01:00</begin>

			<end>2012-12-31+01:00</end>
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>HardCoalResources.xml</DatasetReference>
	<SourceFileReference format="XLSX">sourceFiles/Tabellen_Energiestudie_2013.xlsx</SourceFileReference>
	<Source>
		<ContactPersons>Dr. Harald Andruleit </ContactPersons>
		<URI accessDate="2014-05-02 +15:38">http://www.bgr.bund.de/DE/Themen/Energie/Produkte/energiestudie2013_Zusammenfassung.html</URI>
		<AlternativeURIs />
		<Notes></Notes>
	</Source>
	<CopyrightInformation>Copyrights liegen bei der "Bundesanstalt fuer Geowissenschaften und Rohstoffe (BGR)" vor. Weitere Informationen sind bei dieser Instanz zu erfragen</CopyrightInformation>
	<ImportProcess>
		<Description language="DE">
		Download der Daten als Excel (.xlsx) Format ueber http://www.bgr.bund.de/energiestudie2013.
		Nachfolgende aenderung bzw. Ergaenzung der Einzelnen Spalten um den Identifikator der Laenderkuerzel anhand der  ISO 3166 Alpha-2 
		zu finden unter: http://de.wikipedia.org/wiki/ISO-3166-1-Kodierliste
		Die nun erarbeiteten Daten, muessen nun in eine .csv Datei umgewandelt werden, welche durch den Identifier des Laendercodes zugeordnet werden koennen um in die XML Struktur
		ueberfuehrt zu werden.
		Desweiteren wurde die Tabelle um eine Spalte namens "ID" benannt, welche als eine fortlaufende Nummerierung fuer jedes Land dient. Zeilen mit keinem eindeutigen Wert wurden gemittelt und Zeilen ohne Werte durch ein "-" ersetzt.
		Die fertige Tabelle wird markiert und mittels "Speichern unter" im Datenformat "CSV-(Trennzeichen-getrennt)" gespeichert.
		Die benennung der einzelnen Spalten wurde folgend angeordnet ( ID, Laendercode, Land - sowie die spezifischen Attribute betreffend jeder einelnen Ressource wie z.B. jaehrliche Foerderung etc. )
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/IndiaStateNames_withoutTelangana_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This document holds additional meta-information that is not part of an actual shape file to be processed 
in the context of the BO's ENE project. 
Author: Christian Danowski, Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>India</SpatialScaleHint>
 <!-- Weltweite Informationen-->
	<CovereredTime/>
	<DatasetReference>IndiaStateNames_withoutTelangana.xml</DatasetReference>
 <!-- Name der Datei-->
	<SourceFileReference format="CSV">sourceFiles/IndiaAdmin2.csv</SourceFileReference>
	<Source>
 <!-- Quelle-->
		<ContactPersons>Devdatta Tengshe</ContactPersons>
 <!-- Kontaktperson betreffend des abgegriffenen Datensatzes-->
		<URI accessDate="2015-10-20 +12:00">https://github.com/datameet/maps/tree/master/States</URI>
 <!-- Datum sowie Quelle des abgegriffenen Datensatzes-->
		<AlternativeURIs><!--The following URI represents the direkt download link to the shape file-->
			<URI>https://github.com/datameet/maps/</URI>
		</AlternativeURIs>
		<Notes/>
	</Source>
	<CopyrightInformation>Devdatta Tengshe</CopyrightInformation>
 <!-- Copyright Informationen-->
	<ImportProcess>
		<Description language="DE">
 <!-- Erklaerung der Arbeitsschritte-->
	   		Die Shape-Datei kann direkt zusammen mit den ergaenzenden DBF-, PRJ- sowie SHX-Dateien heruntergeladen werden. 
			Anschließend wurde die Schreibweise einiger indischen States manuell korrigiert 
			und der Spaltenname für die Bezeichner der States wurde zu "NAME" geändert (per QGIS die Attribut-Tabelle bearbeitet.)
			Zusätzlich wurden hierbei noch die States Telangana und Andhra Pradesh zusammengefasst (als Andhra Pradesh).
	   		
	   		Hinweis: Die DBF-Datei wurde zusaetzlich mit Hilfe von Microsoft Excel in eine aequivalente CSV-Datei umgewandelt, um den Datensatz "IndiaStateNames_withoutTelangana.xml" zu erzeugen. 
			Siehe auch "IndiaStateNames_meta.xml".
	   		Die DBF-/CSV-Datei umfasste bereits die englischen Bezeichner jedes States. 
	   		Somit konnte mittels eines eigens entwickelten Java-Programms der 'Entry'-Abschnitt der "IndiaStateNames_withoutTelangana.xml"-Datei mit dieser Information gefuellt werden.
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/ElectricityGeneration_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This example shows how to hold additional meta-information that is not part of an actual data file to be processed 
in the context of the BO's ENE project. 
Primarly, meta-data which document the underlying data-source should be given in such DatasetDescriptions.
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint><!-- 
	For the GI-project "Gespräch mit der Erde", this scale hint always will be "World-wide". In the future, regional data will
	be processed, so that other values might appear. 
	-->
	<CovereredTime>
		<TimePeriod>
			<begin>1970-01-01+01:00</begin>
			<end>2011-12-31+01:00</end>
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>ElectricityGeneration.xml</DatasetReference>
	<SourceFileReference format="CSV">sourceFiles/Strom-Bruttostromerzeugung.csv</SourceFileReference>
	<Source>
		<ContactPersons/>
		<URI accessDate="2014-05-02 +15:38">http://de.wikipedia.org/wiki/Elektrizit%C3%A4t/Tabellen_und_Grafiken</URI>
		<AlternativeURIs/>
		<Notes/>
	</Source>
	<CopyrightInformation/>
	<ImportProcess>
		<Description language="DE">
Auf Wikipedia wurde diese tabelle gefunden und Händisch in Excel eingegeben. Nachdem dies geschehen ist wurde von dieser Tabelle eine CSV Datei erstellt. Diese wurde in das Java Program eingefügt.
	   	</Description>
	</ImportProcess>
</DatasetDescription>
