=== 52North/worldviz/data/xsd/DatasetDescription.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
XML Schema Definition (XSD) for meta-datasets to be used in the context of the WorldViz project. 
Authors: Benno Schmidt, Christian Danowski, Department of Geodesy, Bochum University of Applied Sciences.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="DatasetDescription">
		<xs:annotation>
			<xs:documentation>
			This file holds additional meta-information that is not part of the actual data file. 
			Especially meta-data which document the underlying data-source is given.
      </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SpatialScaleHint" type="SpatialScaleHintType">
					<xs:annotation>
						<xs:documentation>
						In the WorldViz context, most often this scale-hint will be 'World-wide'.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="CovereredTime">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="1" minOccurs="0" name="TimePeriod">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="begin" type="xs:date"/>
										<xs:element name="end" type="xs:date"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="DatasetReference" type="xs:string"/>
				<xs:element name="SourceFileReference">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="format" type="xs:string"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Source">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ContactPersons" type="xs:string"/>
							<xs:element name="URI">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="accessDate" type="xs:string"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="AlternativeURIs">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="URI" type="xs:string">
											<xs:annotation>
												<xs:documentation>Here additional URLs can be documented.</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element maxOccurs="1" minOccurs="0" name="Notes" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CopyrightInformation" type="xs:string"/>
				<xs:element name="ImportProcess">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="1" name="Description" type="Description"/>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="QualityCheck" type="QualityCheck"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:float"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Description">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="languageCode"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="languageCode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EN"/>
			<xs:enumeration value="DE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="QualityCheck">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="date" type="xs:string"/>
				<xs:attribute name="responsiblePerson" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="SpatialScaleHintType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="World-wide"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== 52North/worldviz/data/earth/EarthTimeLapseViewfromSpace_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This example shows how to hold additional meta-information that is not part of an actual data file to be processed 
in the context of the BO's ENE project. 
Primarly, meta-data which document the underlying data-source should be given
 in such DatasetDescriptions.

Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd">
	<SpatialScaleHint>World-wide</SpatialScaleHint>
 <!-- Weltweite abdeckung-->
	<!-- 
	For the GI-project "Gespraech mit der Erde", this scale hint always will be "World-wide". In the future, regional data will
	be processed, so that other values might appear. 
	--> 
	<CovereredTime />
	<DatasetReference>EarthTimeLapseViewfromSpace.xml</DatasetReference>
 <!-- Dateiname-->
	<SourceFileReference />
	<Source>
		<ContactPersons />
		<URI accessDate="2014-10-06 +08:40">https://archive.org/details/EarthTimeLapseViewfromSpace</URI>
 <!-- Zeitangabe sowie Quelle der abgegriffenen Daten-->
		<AlternativeURIs />
		<Notes>On the website, scroll down to find some download links to the video.</Notes>
 <!-- Bemerkungen-->
	</Source>
	<CopyrightInformation>Jeff Kaplan, kaplan@archive.org; Music: Jan Jelinek</CopyrightInformation>
 <!-- Copyright Informationen-->
	<ImportProcess>
		<Description language="DE">
 <!-- Erklaerung der Arbeitsschritte-->
	   		Direkt auf der Webseite kann man nach unten scrollen und dort downloads des Videos finden.
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/ElectricityExport_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This example shows how to hold additional meta-information that is not part of an actual data file to be processed 
in the context of the BO's ENE project. 
Primarly, meta-data which document the underlying data-source should be given in such DatasetDescriptions.
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint><!-- 
	For the GI-project "Gespraech mit der Erde", this scale hint always will be "World-wide". In the future, regional data will
	be processed, so that other values might appear. 
	-->
	<CovereredTime>
		<TimePeriod>
			<begin>2000-01-01+01:00</begin>
			<end>2010-12-31+01:00</end>
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>ElectricityExport.xml</DatasetReference>
	<SourceFileReference format="CSV">sourceFiles/Strom-Export.csv</SourceFileReference>
	<Source>
		<ContactPersons/>
		<URI accessDate="2014-05-02 +15:38">http://de.wikipedia.org/wiki/Elektrizit%C3%A4t/Tabellen_und_Grafiken</URI>
		<AlternativeURIs/>
		<Notes/>
	</Source>
	<CopyrightInformation/>
	<ImportProcess>
		<Description language="DE">
Auf Wikipedia wurde diese Tabelle gefunden und per Hand in Excel uebertragen. Nach dem die Tabelle uebernommen wurde, wurde mithilfe von Excel eine CSV Datei erstellt. Dies wurde in das Java Programm eingefuegt um darzustellen wieviel Strom Exportiert wird. 
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/Sanitation_urbanPopulation_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This example shows how to hold additional meta-information that is not part of an actual data file to be processed 
in the context of the BO's ENE project. 
Primarly, meta-data which document the underlying data-source should be given
 in such DatasetDescriptions.
Authors: Benno Schmidt, Christian Danowski, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint><!-- 
	For the GI-project "Gespraech mit der Erde", this scale hint always will be "World-wide". In the future, regional data will
	be processed, so that other values might appear. 
	-->
	<CovereredTime>
	<!-- 
	Zeitraum, fuer den die thematischen Daten vorliegen
	-->
		<TimePeriod>
			<begin>1990-01-01+01:00</begin>
 <!-- Startzeitraum 
-->	
			<end>2012-12-31+01:00</end>
 <!-- Endzeitraum  
-->
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>Sanitation_urbanPopulation.xml</DatasetReference>
 <!-- Dateiname der xml Datenquelle 
-->
	<SourceFileReference format="CSV">sourceFiles/UNEP-EDE__pop_urban_sanit_perc__1455784563.csv</SourceFileReference>
 <!-- Dateiformat der Quelledatei: Hier Daten stammen aus einer csv Datei 
-->
	<Source>
  <!-- Quelle 
-->
		<ContactPersons/>
 <!-- Falls Kontaktpersonen, fuer die Quelldatei, vorhanden sind 
-->
		<URI accessDate="2016-02-10 +10:00">http://geodata.grid.unep.ch/</URI>
  <!-- Datum, andem die Daten abgerufen wurden, mit Link zur Quelle  
-->
		<AlternativeURIs><!-- Here additional URLs can be documented. -->
			<URI/>
		</AlternativeURIs>
		<Notes/>
 <!-- Zusaetzliche Informationen zu den Daten 
-->
	</Source>
	<CopyrightInformation>UNEP - United Nations Environment Programme; European Commission, Joint Research Centre (JRC)/PBL Netherlands Environmental Assessment Agency.</CopyrightInformation>
  <!-- Anzugebene Copyright Informationen 
-->
	<ImportProcess>
		<Description language="DE">
 <!-- Hier werden die noetigen Schritte beschrieben die noetig waren, um aus der Qulldatei die noetigen Informationen zu extrahieren 
-->
	   		Von obiger URL (siehe 'URI'-Tag) wurde der Datensatz 'Improved Sanitation Coverage - Urban Population as Percentage of Urban Population' als CSV-Datei bezogen. 
			Die ersten vier Zeilen der CSV-Datei enthalten Metadaten wie Titel, Einheit und URL. Diese Zeilen muessen beim Auslesen der Datei geskipped werden. Erst in Zeile fuenf befinden sich die Spaltenueberschriften.
	   		Die CSV-Datei wurde schlie√ülich genutzt, um ueber ein eigens entwickeltes Java-Programm den 'Entries'-Abschnitt der 'CarbonEmissions.xml'-Datei (siehe 'DatasetReference'-Tag) zu erstellen.
	   		Die weiteren Informationen der 'CarbonEmissions.xml'-Datei wurden per Hand eingetragen.
	   	</Description>
		<QualityCheck date="2016-02-10 +11:30" responsiblePerson="Christian Danowski">
 <!-- Datum, andem die Daten auf ihre Qualitaet kontrolliert wurden 
-->
	   		Datensaetze aus generiertem XML-Dokument stichprobenhaft von Hand mit Tabelle im Web verglichen.
	   	</QualityCheck>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/SoftLigniteResources_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This example shows how to hold additional meta-information that is not part of an actual data file to be processed 
in the context of the BO's ENE project. 
Primarly, meta-data which document the underlying data-source should be given in such DatasetDescriptions.
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint><!-- 
	For the GI-project "Gespräch mit der Erde", this scale hint always will be "World-wide". In the future, regional data will
	be processed, so that other values might appear. 
	Letzte Änderung: 02. Juni 2014 von Artur Grzesiuk
	-->
	<CovereredTime>
		<TimePeriod>
			<begin>2012-01-01+01:00</begin>
			<end>2012-12-31+01:00</end>
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>SoftLigniteResources.xml</DatasetReference>
	<SourceFileReference format="XLSX">sourceFiles/Tabellen_Energiestudie_2013.xlsx</SourceFileReference>
	<Source>
		<ContactPersons>Dr. Harald Andruleit </ContactPersons>
		<URI accessDate="2014-05-02 +15:38">http://www.bgr.bund.de/DE/Themen/Energie/Produkte/energiestudie2013_Zusammenfassung.html</URI>
		<AlternativeURIs/>
		<Notes/>
	</Source>
	<CopyrightInformation>Copyrights liegen bei der "Bundesanstalt für Geowissenschaften und Rohstoffe (BGR)" vor. Weitere Informationen sind bei dieser Instanz zu erfragen</CopyrightInformation>
	<ImportProcess>
		<Description language="DE">
		Download der Daten als Excel (.xlsx) Format über http://www.bgr.bund.de/energiestudie2013.
		Nachfolgende Änderung bzw. Ergänzung der Einzelnen Spalten um den Identifikator der Länderkürzel anhand der  ISO 3166 Alpha-2 
		zu finden unter: http://de.wikipedia.org/wiki/ISO-3166-1-Kodierliste
		Die nun erarbeiteten Daten, müssen nun in eine .csv Datei umgewandelt werden, welche durch den Identifier des Ländercodes zugeordnet werden können um in die XML Struktur
		überführt zu werden.
		Desweiteren wurde die Tabelle um eine Spalte namens "ID" benannt, welche als eine fortlaufende Nummerierung für jedes Land dient. Zeilen mit keinem eindeutigen Wert wurden gemittelt und Zeilen ohne Werte durch ein "-" ersetzt.
		Die fertige Tabelle wird markiert und mittels "Speichern unter" im Datenformat "CSV-(Trennzeichen-getrennt)" gespeichert.
		Die benennung der einzelnen Spalten wurde folgend angeordnet ( ID, Ländercode, Land - sowie die spezifischen Attribute betreffend jeder einelnen Ressource wie z.B. jährliche Förderung etc. )
Die Daten der Länder Kosovo und Serbien wurden zu einem Eintrag unter Serbien aggregiert. Gründe: 
1) Es existiert noch kein offizieller ISO-3166-Alpha2 Code für Kosovo; es gibt Stand heute (27.05.2014) nur ein temporäres Kürzel 'XK'. 
2) Die im Projekt verwendete Shape-Datei führt den Kosovo noch als Teil Serbiens, sodass zwecks der Visualisierung die Daten des Kosovo auf die Daten Serbiens addiert wurden.
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/tradeh/imports_partner_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
WorldViz meta-information file.
Note: This file holds additional meta-information that is not part of an actual data file to be processed in the context of WorldViz project. 
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint>
	<CovereredTime>
		<TimePeriod>
			<begin>1998-01-01</begin>
			<end>1998-12-31</end>
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>imports_partner.csv</DatasetReference>
	<SourceFileReference/>
	<Source>
		<ContactPersons/>
		<URI>http://www.economicswebinstitute.org/essays/tradehierarchy.htm</URI>
		<AlternativeURIs/>
		<Notes/>
	</Source>
	<CopyrightInformation>Valentino Piana, Rome - Italy</CopyrightInformation>
	<ImportProcess>
		<Description language="DE">
 	   		Erstellung der Import-Matrix aus der Excel-Tabelle tradeh.xls der ZIP-Datei "http://www.economicswebinstitute.org/essays/tradeh.zip" , 
 	   		Tabellenblatt "Imports partner matrix" (Speichern als CSV.). 
 	   		Vorab wurden noch die LÃ¤ndernamen der Zeilen- und Spaltenbezeichner durch deren zweistelligen ISO3166 country code ersetzt.
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/CountryCodes_simplified_50m_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This document holds additional meta-information that is not part of an actual shape file to be processed 
in the context of the BO's ENE project. 
Author: Christian Danowski, Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint>
 <!-- Weltweite Informationen-->
	<CovereredTime/>
	<DatasetReference>CountryCodes_simplified_50m.xml</DatasetReference>
 <!-- Name der Datei-->
	<SourceFileReference format="CSV">sourceFiles/ne_50m_admin_0_countries.csv</SourceFileReference>
	<Source>
 <!-- Quelle-->
		<ContactPersons>Nathaniel Vaughn KELSO</ContactPersons>
 <!-- Kontaktperson betreffend des abgegriffenen Datensatzes-->
		<URI accessDate="2015-01-20 +12:00">http://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-countries-2/</URI>
 <!-- Datum sowie Quelle des abgegriffenen Datensatzes-->
		<AlternativeURIs><!--The following URI represents the direkt download link to the shape file-->
			<URI>http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip</URI>
		</AlternativeURIs>
		<Notes/>
	</Source>
	<CopyrightInformation>Nathaniel Vaughn KELSO, Project Manager - http://www.naturalearthdata.com/</CopyrightInformation>
 <!-- Copyright Informationen-->
	<ImportProcess>
		<Description language="DE">
 <!-- Erklaerung der Arbeitsschritte-->
	   		Ein ZIP-Archiv mit den weltweiten de-facto Staatsgrenzen kann direkt heruntergeladen werden.
	   		Nach Extraktion in den Ordner "ne_50m_admin_0_countries" steht insbesondere die Datei "ne_50m_admin_0_countries.dbf" zur Verfuegung.
	   		Diese wurde mit Hilfe von Microsoft Excel in eine 
			aequivalente CSV-Datei umgewandelt, um den Datensatz "CountryCodes_simplified_50m.xml" zu erzeugen. 
	   		Die DBF-/CSV-Datei umfasste bereits die ISO3166-ALPHA-2-Codes und ISO3166-ALPHA-3-Codes sowie den englischen Bezeichner jedes Staates. 
	   		Somit konnte mittels eines eigens entwickelten Java-Programms der 'Entry'-Abschnitt der "CountryCodes_simplified_50m.xml"-Datei mit diesen drei Informationen gefuellt werden.
	   		In einem zweiten Verarbeitungsschritt wurde die "CountryCodes_simplified_50m.xml"-Datei in ein Java-Programm eingelesen und es wurde mittels des Java-Objects 'Locale' an 
	   		jeden Staats-Eintrag der deutsche Bezeichner angefuegt.
			
			Update(29.04.2015): Der Eintrag Somalialand wurde manuell geaendert. Da es kein international anerkanntes Land ist, existiert kein offizielles ISO3166-Kennzeichen. 
			Stattdessen wurde einfach das Kuerzel 'SOL' benutzt und als ISO-Code hinterlegt. In der originaeren Shape-Datei wurde diese Umbenennung ebenfalls durchgefuehrt.
			Hintergrund: Vorher waren nichtexistente Eintraege mit '-99' belegt. Damit dies jedoch von der Programmlogik richtig verarbeitet wird und auch in der visualisierten Szene dargestellt wird, 
			muss das Land eindeutig sowohl innerhalb der XML-Datei als auch in der originaeren Shape-Datei bezeichnet sein, um Verwechselungen zu vermeiden. 
			
			Update(29.04.2015): Eintrag Kosovo ergaenzt. Auch hier ist wie oben eigentlich kein offizielles ISO3166-Kennzeichen existent. Daher wurden die Kuerzel 'KV' und 'KSV' benutzt.
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/ElectricityConsumption_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This example shows how to hold additional meta-information that is not part of an actual data file to be processed 
in the context of the BO's ENE project. 
Primarly, meta-data which document the underlying data-source should be given in such DatasetDescriptions.
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint><!-- 
	For the GI-project "GesprÃ¤ch mit der Erde", this scale hint always will be "World-wide". In the future, regional data will
	be processed, so that other values might appear. 
	-->
	<CovereredTime>
		<TimePeriod>
			<begin>2000-01-01+01:00</begin>
			<end>2009-12-31+01:00</end>
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>ElectricityConsumption.xml</DatasetReference>
	<SourceFileReference format="CSV">sourceFiles/Strom-Verbrauch.csv</SourceFileReference>
	<Source>
		<ContactPersons/>
		<URI accessDate="2014-05-02 +15:38">
http://de.wikipedia.org/wiki/Elektrizit%C3%A4t/Tabellen_und_Grafiken</URI>
		<AlternativeURIs/>
		<Notes/>
	</Source>
	<CopyrightInformation/>
	<ImportProcess>
		<Description language="DE">
Aus Wikipedia wurde diese Tabelle von Hand kopiert. Nach dem dies geschehen ist wurde mit Excel eine CSV erstellt.
	   	</Description>
	</ImportProcess>
</DatasetDescription>

=== 52North/worldviz/data/earth/NuclearAccidents_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Dataformat.xsl"?>
<!--
This example shows how to hold additional meta-information that is not part of an actual data file to be processed 
in the context of the BO's ENE project. 
Primarly, meta-data which document the underlying data-source should be given
 in such DatasetDescriptions.

Author: Benno Schmidt, Artur Grzesiuk, Christian Danowski, Department of Geodesy, Bochum University of Applied Sciences.
-->
<DatasetDescription version="0.1" xsi:noNamespaceSchemaLocation="xsd/DatasetDescription.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SpatialScaleHint>World-wide</SpatialScaleHint><!-- 
	For the GI-project "Gespräch mit der Erde", this scale hint always will be "World-wide". In the future, regional data will
	be processed, so that other values might appear. 
	-->
	<CovereredTime>
		<TimePeriod>
			<begin>1945-08-21+01:00</begin><!-- Beginn der Aufzeichnungen der Nuklearen Unfälle-->
			<end>2011-03-11+01:00</end><!-- Letzter verzeichneter Unfall-->
		</TimePeriod>
	</CovereredTime>
	<DatasetReference>NuclearAccidents.xml</DatasetReference>
	<SourceFileReference format="CSV">sourceFiles/Kernkraftwerke_Unfaelle.csv</SourceFileReference>
	<Source>
		<ContactPersons>none</ContactPersons>
		<URI accessDate="2014-05-12 +10:00">http://de.wikipedia.org/wiki/Liste_von_Unf%C3%A4llen_in_kerntechnischen_Anlagen</URI>
		<AlternativeURIs>
			<URI>
			http://de.wikipedia.org/wiki/Internationale_Bewertungsskala_für_nukleare_Ereignisse <!--INES-Skala für sicherheitsrelevante Ereignisse-->
			</URI>
			<URI/>
		</AlternativeURIs>
	</Source>
	<CopyrightInformation>unknown</CopyrightInformation>
	<ImportProcess>
		<Description language="DE">
	   		Die Daten der Wikipedia-Seite wurden händisch in der Excel-Tabelle 'Kernkraftwerke_Unfaelle' zusammengetragen. Die Koordinaten der einzelnen Einträge wurden dabei per GoogleMaps grob abgegriffen. 
	   		Nicht jeder Datensatz konnte auf Grundlage des Wikipedia-Artikels eindeutig georeferenziert werden. In einem solchen Fall wurde hilfsmäßig eine grobe Koordinate des Bundesstaates gewählt.
	   		Anschließend wurde die Tabelle als CSV-Datei exportiert. 
	   		Diese wurde dann benutzt, um mittels des selbst entwickelten Java-Programms den 'Entries'-Teil der 'NuclearAccidents.xml'-Datei zu füllen. 
	   	</Description>
	</ImportProcess>
</DatasetDescription>
