=== 52North/worldviz/data/earth/xsd/Dataset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
XML Schema Definition (XSD) for datasets that will be processed in the context of the WorldViz project. 
Authors: Benno Schmidt, Christian Danowski, Department of Geodesy, Bochum University of Applied Sciences.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Dataset">
		<xs:annotation>
			<xs:documentation>
			This file holds the complete information needed to set-up a visualization (e.g., inside the Erlebnisraum).
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="GeneralInformation">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Theme">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Title" type="Title"/>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Description" type="Description"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Unit">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Title" type="Title"/>
										<xs:element maxOccurs="1" minOccurs="0" name="Code" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="PublicReference" type="xs:string"/>
							<xs:element name="MetadataReference" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="TableStructure">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="Property">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Title" type="Title"/>
										<xs:element maxOccurs="1" minOccurs="0" name="TimeReference">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="begin" type="xs:date"/>
													<xs:element name="end" type="xs:date"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Description" type="Description"/>
										<xs:element minOccurs="0" name="GeoReference">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="CRS" type="crs"/>
												</xs:sequence>
												<xs:attribute name="featureType" type="xs:string"/>
												<xs:attribute name="externalGeometries" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="dataType" type="xs:string" use="optional"/>
									<xs:attribute name="uniqueID" type="xs:boolean" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Entries">
					<xs:annotation>
						<xs:documentation>usw.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="Entry">
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Value" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:float"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Description">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="languageCode"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="Title">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="languageCode"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="languageCode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EN"/>
			<xs:enumeration value="DE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="crs">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ENE:CountriesWorldwide:iso3166-2"/>
			<xs:enumeration value="EPSG:4326"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== 52North/worldviz/data/earth/ElectricityImport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This sample dataset holds the complete information needed to set-up a visualization for the BO's ENE project. 
Authors: Christian Danowski, Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<Dataset version="0.1" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GeneralInformation>
		<Theme>
			<Title language="EN">Electricity Import</Title><!-- Titel bezogen auf die Sprache: Englisch-->
			<Title language="DE">Stromimport</Title><!-- Titel bezogen auf die Sprache: Deutsch-->
			<Description language="EN">This dataset gives the electricity import for the years 2000, 2005-2010 in terrawatts per hours for the World's countries.</Description><!-- Erklärung auf Englisch-->
			<Description language="DE">Dieser Datensatz enthält staatenweise den Stromimport in Terawattstunden für die Jahre 2000, 2005-2010.</Description><!-- Erklärung auf Deutsch-->
		</Theme>
		<Unit>
			<Title>Terawatt hours per year</Title><!-- Einheiten auf welche sich die gegebenen Daten beziehen: Englisch-->
			<Code>TWh/a</Code><!-- Einheiten Kodiert-->
		</Unit>
		<PublicReference>Wikipedia</PublicReference>
		<MetadataReference>ElectricityImport_meta.xml</MetadataReference><!-- Referenz der Metadatendatei-->
	</GeneralInformation>
	<TableStructure>
		<Property dataType="ENE:iso3166-2" uniqueID="true"><!-- Hier verwendete Kodierliste bezüglich der Länderkürzel-->
			<Title>Country code</Title><!-- Titel-->
			<Description>Country code ISO 3166-2</Description><!-- For geo-referenced 
properties, a GeoReference element should be present: -->
			<GeoReference featureType="ENE:CountryCode" externalGeometries="true">
				<CRS>ENE:CountriesWorldwide:iso3166-2</CRS>
			</GeoReference>
		</Property>
		<Property dataType="Float">
			<Title>2000</Title><!-- For time-referenced 
properties, a TimeReference element should be present: -->
			<TimeReference>
				<begin>2000-01-01+01:00</begin>
				<end>2000-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2005</Title>
			<TimeReference>
				<begin>2005-01-01+01:00</begin>
				<end>2005-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2006</Title>
			<TimeReference>
				<begin>2006-01-01+01:00</begin>
				<end>2006-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2007</Title>
			<TimeReference>
				<begin>2007-01-01+01:00</begin>
				<end>2007-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2008</Title>
			<TimeReference>
				<begin>2008-01-01+01:00</begin>
				<end>2008-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2009</Title>
			<TimeReference>
				<begin>2009-01-01+01:00</begin>
				<end>2009-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2010</Title>
			<TimeReference>
				<begin>2010-01-01+01:00</begin>
				<end>2010-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>AR</Value>
			<Value>7.25</Value>
			<Value>8.02</Value>
			<Value>7.42</Value>
			<Value>10.28</Value>
			<Value>8.46</Value>
			<Value>8.60</Value>
			<Value>10.30</Value>
		</Entry>
		<Entry>
			<Value>AT</Value>
			<Value>13.82</Value>
			<Value>20.40</Value>
			<Value>21.26</Value>
			<Value>22.13</Value>
			<Value>19.80</Value>
			<Value>19.54</Value>
			<Value>19.75</Value>
		</Entry>
		<Entry>
			<Value>BE</Value>
			<Value>11.65</Value>
			<Value>14.33</Value>
			<Value>18.85</Value>
			<Value>15.82</Value>
			<Value>17.16</Value>
			<Value>9.49</Value>
			<Value>12.41</Value>
		</Entry>
		<Entry>
			<Value>BR</Value>
			<Value>43.00</Value>
			<Value>39.20</Value>
			<Value>41.45</Value>
			<Value>40.87</Value>
			<Value>42.90</Value>
			<Value>40.75</Value>
			<Value>36.63</Value>
		</Entry>
		<Entry>
			<Value>CA</Value>
			<Value>12.69</Value>
			<Value>19.32</Value>
			<Value>23.41</Value>
			<Value>19.56</Value>
			<Value>23.61</Value>
			<Value>17.52</Value>
			<Value>18.79</Value>
		</Entry>
		<Entry>
			<Value>CH</Value>
			<Value>24.33</Value>
			<Value>38.35</Value>
			<Value>33.80</Value>
			<Value>34.82</Value>
			<Value>31.60</Value>
			<Value>31.37</Value>
			<Value>33.40</Value>
		</Entry>
		<Entry>
			<Value>DE</Value>
			<Value>45.13</Value>
			<Value>56.86</Value>
			<Value>48.46</Value>
			<Value>45.95</Value>
			<Value>41.67</Value>
			<Value>41.86</Value>
			<Value>42.96</Value>
		</Entry>
		<Entry>
			<Value>DK</Value>
			<Value>8.42</Value>
			<Value>12.94</Value>
			<Value>6.77</Value>
			<Value>10.43</Value>
			<Value>12.82</Value>
			<Value>11.21</Value>
			<Value>10.60</Value>
		</Entry>
		<Entry>
			<Value>FI</Value>
			<Value>12.21</Value>
			<Value>17.95</Value>
			<Value>14.12</Value>
			<Value>15.42</Value>
			<Value>16.11</Value>
			<Value>15.46</Value>
			<Value>15.72</Value>
		</Entry>
		<Entry>
			<Value>GR</Value>
			<Value>1.73</Value>
			<Value>5.62</Value>
			<Value>6.14</Value>
			<Value>6.41</Value>
			<Value>7.58</Value>
			<Value>7.60</Value>
			<Value>8.52</Value>
		</Entry>
		<Entry>
			<Value>HK</Value>
			<Value>10.20</Value>
			<Value>11.00</Value>
			<Value>10.90</Value>
			<Value>10.96</Value>
			<Value>11.30</Value>
			<Value>11.59</Value>
			<Value>11.05</Value>
		</Entry>
		<Entry>
			<Value>HU</Value>
			<Value>9.52</Value>
			<Value>15.64</Value>
			<Value>15.39</Value>
			<Value>14.68</Value>
			<Value>12.77</Value>
			<Value>10.97</Value>
			<Value>9.90</Value>
		</Entry>
		<Entry>
			<Value>IN</Value>
			<Value>1.54</Value>
			<Value>1.76</Value>
			<Value>2.96</Value>
			<Value>5.23</Value>
			<Value>9.25</Value>
			<Value>10.53</Value>
			<Value>11.00</Value>
		</Entry>
		<Entry>
			<Value>IT</Value>
			<Value>44.83</Value>
			<Value>50.26</Value>
			<Value>46.60</Value>
			<Value>48.93</Value>
			<Value>43.43</Value>
			<Value>46.57</Value>
			<Value>45.76</Value>
		</Entry>
		<Entry>
			<Value>NL</Value>
			<Value>22.95</Value>
			<Value>23.69</Value>
			<Value>27.35</Value>
			<Value>23.14</Value>
			<Value>24.97</Value>
			<Value>15.45</Value>
			<Value>15.58</Value>
		</Entry>
		<Entry>
			<Value>NO</Value>
			<Value>1.47</Value>
			<Value>3.65</Value>
			<Value>9.80</Value>
			<Value>5.29</Value>
			<Value>3.41</Value>
			<Value>5.65</Value>
			<Value>14.67</Value>
		</Entry>
		<Entry>
			<Value>SE</Value>
			<Value>18.31</Value>
			<Value>14.58</Value>
			<Value>17.54</Value>
			<Value>16.05</Value>
			<Value>12.75</Value>
			<Value>13.77</Value>
			<Value>14.93</Value>
		</Entry>
		<Entry>
			<Value>US</Value>
			<Value>48.59</Value>
			<Value>44.53</Value>
			<Value>42.69</Value>
			<Value>51.40</Value>
			<Value>57.02</Value>
			<Value>52.19</Value>
			<Value>45.23</Value>
		</Entry>
		<Entry>
			<Value>UZ</Value>
			<Value>14.03</Value>
			<Value>11.42</Value>
			<Value>11.82</Value>
			<Value>11.36</Value>
			<Value>11.46</Value>
			<Value>11.58</Value>
			<Value>11.60</Value>
		</Entry>
		<Entry>
			<Value>ZA</Value>
			<Value>5.29</Value>
			<Value>11.08</Value>
			<Value>10.62</Value>
			<Value>11.35</Value>
			<Value>10.57</Value>
			<Value>12.30</Value>
			<Value>12.19</Value>
		</Entry>
	</Entries>
</Dataset>

=== 52North/worldviz/data/earth/CountriesShape.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This sample dataset holds the complete information needed to set-up a visualization for the BO's ENE project. 
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<Dataset version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd">
	<GeneralInformation>
		<Theme>
			<Title language="EN">World countries as shape</Title>
			<Title language="DE">Shape mit weltweiten Staatsgrenzen</Title>
			<Description language="DE">
				Dieses Dokument verweist auf den Quelldatei mit den Geometrien der Staatsgrenzen weltweit 
				(ESRI-Shape-Format). 
				Pro Staat werden die Staatsgrenzen in Form eines Multipolygons vorgehalten.
				In der Shape-Datei sind unter anderem Länderkürzel im ISO3166-ALPHA-2 - Format angegeben, so dass über die "CountryCodes.xml"
				im ENE-Projekt eine Georeferenzierung länderbezogener statistischer Daten möglich wird.
			</Description>
		</Theme>
		<Unit />
		<PublicReference>Bjorn Sandvik - thematicmapping.org</PublicReference>
		<MetadataReference>CountriesShape_meta.xml</MetadataReference>
	</GeneralInformation>
	<TableStructure>
		<Property dataType="String">
			<Title>Shape file name</Title>
			<GeoReference featureType="ENE:EsriShape">
				<CRS>EPSG:4326</CRS>
			</GeoReference>
		</Property>
		<Property dataType="String">
			<Title>Database file name</Title>
		</Property>
		<Property dataType="String">
			<Title>Spatial extent</Title>
			<Description />
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>TM_WORLD_BORDERS-0.3.shp</Value>
			<Value>TM_WORLD_BORDERS-0.3.dbf</Value>
			<Value>-180,-90,180,90</Value>
		</Entry>
	</Entries>
</Dataset>

=== 52North/worldviz/data/earth/ElectricityExport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This sample dataset holds the complete information needed to set-up a visualization for the BO's ENE project. 
Authors: Christian Danowski, Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<Dataset version="0.1" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GeneralInformation>
		<Theme>
			<Title language="EN">Electricity Export</Title><!-- Titel bezogen auf die Sprache: Englisch-->
			<Title language="DE">Stromexport</Title><!-- Titel bezogen auf die Sprache: Deutsch-->
			<Description language="EN">This dataset gives the electricity export for the years 2000, 2005-2010 in terrawatts per hours for the World's countries.</Description><!-- Erklaerung auf Englisch-->
			<Description language="DE">Dieser Datensatz enthaelt staatenweise den Stromexport in Terawattstunden fuer die Jahre 2000, 2005-2010.</Description><!-- Erklaerung auf Deutsch-->
		</Theme>
		<Unit>
			<Title>Terawatt hours per year</Title><!-- Einheiten auf welche sich die gegebenen Daten beziehen: Englisch-->
			<Code>TWh/a</Code><!-- Einheiten Kodiert-->
		</Unit>
		<PublicReference>Wikipedia</PublicReference>
		<MetadataReference>ElectricityExport_meta.xml</MetadataReference><!-- Referenz der Metadatendatei-->
	</GeneralInformation>
	<TableStructure>
		<Property dataType="ENE:iso3166-2" uniqueID="true"><!-- Hier verwendete Kodierliste bezueglich der Laenderkuerzel-->
			<Title>Country code</Title><!-- Titel-->
			<Description>Country code ISO 3166-2</Description><!-- For geo-referenced 
properties, a GeoReference element should be present: -->
			<GeoReference featureType="ENE:CountryCode" externalGeometries="true">
				<CRS>ENE:CountriesWorldwide:iso3166-2</CRS>
			</GeoReference>
		</Property>
		<Property dataType="Float">
			<Title>2000</Title><!-- For time-referenced 
properties, a TimeReference element should be present: -->
			<TimeReference>
				<begin>2000-01-01+01:00</begin>
				<end>2000-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2005</Title>
			<TimeReference>
				<begin>2005-01-01+01:00</begin>
				<end>2005-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2006</Title>
			<TimeReference>
				<begin>2006-01-01+01:00</begin>
				<end>2006-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2007</Title>
			<TimeReference>
				<begin>2007-01-01+01:00</begin>
				<end>2007-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2008</Title>
			<TimeReference>
				<begin>2008-01-01+01:00</begin>
				<end>2008-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2009</Title>
			<TimeReference>
				<begin>2009-01-01+01:00</begin>
				<end>2009-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2010</Title>
			<TimeReference>
				<begin>2010-01-01+01:00</begin>
				<end>2010-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>AT</Value>
			<Value>15.19</Value>
			<Value>17.73</Value>
			<Value>14.41</Value>
			<Value>15.51</Value>
			<Value>14.93</Value>
			<Value>18.76</Value>
			<Value>17.53</Value>
		</Entry>
		<Entry>
			<Value>BE</Value>
			<Value>7.32</Value>
			<Value>8.02</Value>
			<Value>8.70</Value>
			<Value>9.04</Value>
			<Value>6.56</Value>
			<Value>11.32</Value>
			<Value>11.84</Value>
		</Entry>
		<Entry>
			<Value>BG</Value>
			<Value>5.58</Value>
			<Value>8.38</Value>
			<Value>8.88</Value>
			<Value>7.53</Value>
			<Value>8.44</Value>
			<Value>7.74</Value>
			<Value>9.36</Value>
		</Entry>
		<Entry>
			<Value>CA</Value>
			<Value>48.52</Value>
			<Value>42.93</Value>
			<Value>41.54</Value>
			<Value>50.12</Value>
			<Value>55.73</Value>
			<Value>50.87</Value>
			<Value>43.91</Value>
		</Entry>
		<Entry>
			<Value>CH</Value>
			<Value>31.40</Value>
			<Value>32.00</Value>
			<Value>31.10</Value>
			<Value>36.88</Value>
			<Value>32.74</Value>
			<Value>33.53</Value>
			<Value>32.88</Value>
		</Entry>
		<Entry>
			<Value>CN</Value>
			<Value>10.30</Value>
			<Value>11.19</Value>
			<Value>12.27</Value>
			<Value>14.57</Value>
			<Value>16.64</Value>
			<Value>17.39</Value>
			<Value>19.06</Value>
		</Entry>
		<Entry>
			<Value>CZ</Value>
			<Value>18.74</Value>
			<Value>24.99</Value>
			<Value>24.10</Value>
			<Value>26.36</Value>
			<Value>19.99</Value>
			<Value>22.23</Value>
			<Value>21.59</Value>
		</Entry>
		<Entry>
			<Value>DE</Value>
			<Value>42.08</Value>
			<Value>61.43</Value>
			<Value>65.44</Value>
			<Value>62.51</Value>
			<Value>61.77</Value>
			<Value>54.13</Value>
			<Value>57.92</Value>
		</Entry>
		<Entry>
			<Value>DK</Value>
			<Value>7.75</Value>
			<Value>11.57</Value>
			<Value>13.70</Value>
			<Value>11.38</Value>
			<Value>11.36</Value>
			<Value>10.87</Value>
			<Value>11.73</Value>
		</Entry>
		<Entry>
			<Value>ES</Value>
			<Value>7.83</Value>
			<Value>11.56</Value>
			<Value>12.37</Value>
			<Value>14.52</Value>
			<Value>16.92</Value>
			<Value>14.86</Value>
			<Value>13.52</Value>
		</Entry>
		<Entry>
			<Value>FR</Value>
			<Value>73.17</Value>
			<Value>68.39</Value>
			<Value>71.86</Value>
			<Value>67.60</Value>
			<Value>58.74</Value>
			<Value>44.45</Value>
			<Value>66.60</Value>
		</Entry>
		<Entry>
			<Value>MZ</Value>
			<Value>5.77</Value>
			<Value>12.00</Value>
			<Value>12.83</Value>
			<Value>11.82</Value>
			<Value>11.21</Value>
			<Value>12.94</Value>
			<Value>13.00</Value>
		</Entry>
		<Entry>
			<Value>NL</Value>
			<Value>4.03</Value>
			<Value>5.40</Value>
			<Value>5.89</Value>
			<Value>5.57</Value>
			<Value>9.12</Value>
			<Value>10.56</Value>
			<Value>12.81</Value>
		</Entry>
		<Entry>
			<Value>PY</Value>
			<Value>47.36</Value>
			<Value>43.79</Value>
			<Value>45.71</Value>
			<Value>45.12</Value>
			<Value>46.30</Value>
			<Value>45.04</Value>
			<Value>43.38</Value>
		</Entry>
		<Entry>
			<Value>RU</Value>
			<Value>22.85</Value>
			<Value>22.52</Value>
			<Value>20.93</Value>
			<Value>18.47</Value>
			<Value>20.74</Value>
			<Value>17.92</Value>
			<Value>19.01</Value>
		</Entry>
		<Entry>
			<Value>SI</Value>
			<Value>5.55</Value>
			<Value>7.56</Value>
			<Value>7.02</Value>
			<Value>5.91</Value>
			<Value>7.82</Value>
			<Value>9.22</Value>
			<Value>10.14</Value>
		</Entry>
		<Entry>
			<Value>UA</Value>
			<Value>6.50</Value>
			<Value>10.07</Value>
			<Value>12.52</Value>
			<Value>12.55</Value>
			<Value>8.83</Value>
			<Value>7.96</Value>
			<Value>8.00</Value>
		</Entry>
		<Entry>
			<Value>US</Value>
			<Value>14.83</Value>
			<Value>19.79</Value>
			<Value>24.27</Value>
			<Value>20.14</Value>
			<Value>24.20</Value>
			<Value>18.14</Value>
			<Value>19.41</Value>
		</Entry>
		<Entry>
			<Value>UZ</Value>
			<Value>12.75</Value>
			<Value>11.50</Value>
			<Value>11.90</Value>
			<Value>11.44</Value>
			<Value>11.55</Value>
			<Value>11.50</Value>
			<Value>11.66</Value>
		</Entry>
		<Entry>
			<Value>ZA</Value>
			<Value>3.97</Value>
			<Value>13.42</Value>
			<Value>13.59</Value>
			<Value>14.50</Value>
			<Value>14.17</Value>
			<Value>14.05</Value>
			<Value>14.65</Value>
		</Entry>
	</Entries>
</Dataset>

=== 52North/worldviz/data/earth/LandCover.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This sample dataset holds the complete information needed to set-up a visualization for the BO's ENE project. 
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<Dataset version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd">
	<GeneralInformation>
		<Theme>
			<Title language="EN">Land cover classification map of the World</Title>
			<Title language="DE">Landnutzungsklassifikation weltweit</Title>
			<Description>
			This image shows global land cover types in different colors. Each land cover has a different effect on 
			carbon and climate cycles. Snow and ice cool the planet by reflecting sunlight. Tropical rainforests are 
			part of an intricate land-atmosphere relationship that is disturbed by land cover changes such as 
			deforestation. Perhaps the most significant human alteration of land cover is the creation of large areas 
			of agricultural land. For more information, see http://earthobservatory.nasa.gov/IOTD/view.php?id=2695
			</Description>
		</Theme>
		<Unit />
		<PublicReference>NASA Earth Observatory/NOAA NGDC 2012</PublicReference>
		<MetadataReference>LandCover_meta.xml</MetadataReference>
	</GeneralInformation>
	<TableStructure>
		<Property dataType="">
			<Title>Spatial extent</Title>
			<Description />
			<GeoReference featureType="ENE:Bitmap" externalGeometries="false">
				<CRS>EPSG:4326</CRS>
			</GeoReference>
		</Property>
		<Property dataType="String">
			<Title>File name</Title>
		</Property>
		<Property dataType="String">
			<Title>Image size</Title>
			<Description>Image size in pixels</Description>
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>-180,-90,180,90</Value>
			<Value>LandCover.jpg</Value>
			<Value>2048x1024</Value>
		</Entry>
	</Entries>
</Dataset>

=== 52North/worldviz/data/earth/CountriesShape_simplified_110m.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This sample dataset holds the complete information needed to set-up a visualization for the BO's ENE project. 
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<Dataset version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd">
	<GeneralInformation>
		<Theme>
			<Title language="EN">World countries as shape (with simplified borders in a scale of 1:110m)</Title>
			<Title language="DE">Shape mit weltweiten Staatsgrenzen (Grenzen sind vereinfacht in einem Maßstab von 1:110m)</Title>
			<Description language="DE">
				Dieses Dokument verweist auf den Quelldatei mit den Geometrien der Staatsgrenzen weltweit 
				(ESRI-Shape-Format). 
				Pro Staat werden die de facto Staatsgrenzen in Form eines Multipolygons vorgehalten.
				In der Shape-Datei sind unter anderem Länderkürzel im ISO3166-ALPHA-2 - Format angegeben, so dass über die "CountryCodes_simplified_110m.xml"
				im ENE-Projekt eine Georeferenzierung länderbezogener statistischer Daten möglich wird.
			</Description>
		</Theme>
		<Unit />
		<PublicReference>Nathaniel Vaughn KELSO, Project Manager - http://www.naturalearthdata.com/</PublicReference>
		<MetadataReference>CountriesShape_simplified_110m_meta.xml</MetadataReference>
	</GeneralInformation>
	<TableStructure>
		<Property dataType="String">
			<Title>Shape file name</Title>
			<GeoReference featureType="ENE:EsriShape">
				<CRS>EPSG:4326</CRS>
			</GeoReference>
		</Property>
		<Property dataType="String">
			<Title>Database file name</Title>
		</Property>
		<Property dataType="String">
			<Title>Spatial extent</Title>
			<Description />
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>ne_110m_admin_0_countries.shp</Value>
			<Value>ne_110m_admin_0_countries.dbf</Value>
			<Value>-180,-90,180,90</Value>
		</Entry>
	</Entries>
</Dataset>
