=== 52North/worldviz/data/earth/xsd/Dataset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
XML Schema Definition (XSD) for datasets that will be processed in the context of the WorldViz project. 
Authors: Benno Schmidt, Christian Danowski, Department of Geodesy, Bochum University of Applied Sciences.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Dataset">
		<xs:annotation>
			<xs:documentation>
			This file holds the complete information needed to set-up a visualization (e.g., inside the Erlebnisraum).
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="GeneralInformation">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Theme">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Title" type="Title"/>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Description" type="Description"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Unit">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Title" type="Title"/>
										<xs:element maxOccurs="1" minOccurs="0" name="Code" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="PublicReference" type="xs:string"/>
							<xs:element name="MetadataReference" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="TableStructure">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="Property">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Title" type="Title"/>
										<xs:element maxOccurs="1" minOccurs="0" name="TimeReference">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="begin" type="xs:date"/>
													<xs:element name="end" type="xs:date"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Description" type="Description"/>
										<xs:element minOccurs="0" name="GeoReference">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="CRS" type="crs"/>
												</xs:sequence>
												<xs:attribute name="featureType" type="xs:string"/>
												<xs:attribute name="externalGeometries" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="dataType" type="xs:string" use="optional"/>
									<xs:attribute name="uniqueID" type="xs:boolean" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Entries">
					<xs:annotation>
						<xs:documentation>usw.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="Entry">
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Value" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:float"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Description">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="languageCode"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="Title">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="languageCode"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="languageCode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EN"/>
			<xs:enumeration value="DE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="crs">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ENE:CountriesWorldwide:iso3166-2"/>
			<xs:enumeration value="EPSG:4326"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== 52North/worldviz/data/earth/IndiaTreeCover2011.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This sample dataset holds the complete information needed to set-up a visualization for the BO's ENE project. 
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<Dataset version="0.1" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GeneralInformation>
		<Theme>
			<Title language="EN">Tree Cover of India States in 2011</Title>
			<Title language="DE">Baumabdeckung der indischen States im Jahr 2011</Title>
			<Description language="DE">
				Die Datei enthält Informationen über die Baumabdeckung der indischen States im Jahr 2011.
			</Description>
		</Theme>
		<Unit/>
		<PublicReference>ENVIS Centre, Ministry of Environment and Forest, Govt. of India</PublicReference>
		<MetadataReference>IndiaTreeCover2011_meta.xml</MetadataReference>
	</GeneralInformation>
	<TableStructure>
		<Property dataType="String" uniqueID="true">
			<Title>States/UTs</Title>
			<Description>english name of the state</Description>
			<GeoReference featureType="ENE:StateName" externalGeometries="true">
				<CRS>ENE:CountryStates:name</CRS>
			</GeoReference>
		</Property>
		<Property dataType="Float">
			<Title>Area (GA)</Title>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>Reserved Forests</Title>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>Protected Forests</Title>
			<Description/>
		</Property>
<Property dataType="Float">
			<Title>Unclassified Forests</Title>
			<Description/>
		</Property>	
<Property dataType="Float">
			<Title>Total - RFA</Title>
			<Description/>
		</Property>			
		<Property dataType="Float">
			<Title>Tree Cover % of GA</Title>
			<Description/>
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>Andaman and Nicobar Islands</Value>
			<Value>8249.00</Value>
			<Value>5613.00</Value>
			<Value>1558.00</Value>
			<Value>0.00</Value>
			<Value>7171.00</Value>
			<Value>86.93</Value>
		</Entry>
		<Entry>
			<Value>Andhra Pradesh</Value>
			<Value>275069.00</Value>
			<Value>50479.00</Value>
			<Value>12365.00</Value>
			<Value>970.00</Value>
			<Value>63814.00</Value>
			<Value>23.20</Value>
		</Entry>
		<Entry>
			<Value>Arunachal Pradesh</Value>
			<Value>83743.00</Value>
			<Value>10723.00</Value>
			<Value>9779.00</Value>
			<Value>31039.00</Value>
			<Value>51541.00</Value>
			<Value>61.55</Value>
		</Entry>
		<Entry>
			<Value>Assam</Value>
			<Value>78438.00</Value>
			<Value>17864.00</Value>
			<Value>0.00</Value>
			<Value>8968.00</Value>
			<Value>26832.00</Value>
			<Value>34.21</Value>
		</Entry>
		<Entry>
			<Value>Bihar</Value>
			<Value>94163.00</Value>
			<Value>693.00</Value>
			<Value>5779.00</Value>
			<Value>1.00</Value>
			<Value>6473.00</Value>
			<Value>6.87</Value>
		</Entry>
		<Entry>
			<Value>Chandigarh</Value>
			<Value>114.00</Value>
			<Value>32.00</Value>
			<Value>0.00</Value>
			<Value>3.00</Value>
			<Value>35.00</Value>
			<Value>30.70</Value>
		</Entry>
		<Entry>
			<Value>Chhattisgarh</Value>
			<Value>135191.00</Value>
			<Value>25782.00</Value>
			<Value>24036.00</Value>
			<Value>9954.00</Value>
			<Value>59772.00</Value>
			<Value>44.21</Value>
		</Entry>
		<Entry>
			<Value>Dadra and NagarHaveli</Value>
			<Value>491.00</Value>
			<Value>199.00</Value>
			<Value>5.00</Value>
			<Value>0.00</Value>
			<Value>204.00</Value>
			<Value>41.55</Value>
		</Entry>
		<Entry>
			<Value>Daman and Diu</Value>
			<Value>112.00</Value>
			<Value>0.24</Value>
			<Value>0.00</Value>
			<Value>8.03</Value>
			<Value>8.00</Value>
			<Value>7.38</Value>
		</Entry>
		<Entry>
			<Value>Delhi</Value>
			<Value>1483.00</Value>
			<Value>78.00</Value>
			<Value>7.00</Value>
			<Value>0.00</Value>
			<Value>85.00</Value>
			<Value>5.73</Value>
		</Entry>
		<Entry>
			<Value>Goa</Value>
			<Value>3702.00</Value>
			<Value>253.00</Value>
			<Value>0.00</Value>
			<Value>972.00</Value>
			<Value>1225.00</Value>
			<Value>33.09</Value>
		</Entry>
		<Entry>
			<Value>Gujarat</Value>
			<Value>196022.00</Value>
			<Value>14373.00</Value>
			<Value>2886.00</Value>
			<Value>4388.00</Value>
			<Value>21647.00</Value>
			<Value>11.04</Value>
		</Entry>
		<Entry>
			<Value>Haryana</Value>
			<Value>44212.00</Value>
			<Value>249.00</Value>
			<Value>1158.00</Value>
			<Value>152.00</Value>
			<Value>1559.00</Value>
			<Value>3.53</Value>
		</Entry>
		<Entry>
			<Value>Himachal Pradesh</Value>
			<Value>55673.00</Value>
			<Value>1898.00</Value>
			<Value>33130.00</Value>
			<Value>2005.00</Value>
			<Value>37033.00</Value>
			<Value>66.52</Value>
		</Entry>
		<Entry>
			<Value>Jammu and Kashmir</Value>
			<Value>222236.00</Value>
			<Value>17643.00</Value>
			<Value>2551.00</Value>
			<Value>36.00</Value>
			<Value>20230.00</Value>
			<Value>9.10</Value>
		</Entry>
		<Entry>
			<Value>Jharkhand</Value>
			<Value>79714.00</Value>
			<Value>4387.00</Value>
			<Value>19185.00</Value>
			<Value>33.00</Value>
			<Value>23605.00</Value>
			<Value>29.61</Value>
		</Entry>
		<Entry>
			<Value>Karnataka</Value>
			<Value>191791.00</Value>
			<Value>28690.00</Value>
			<Value>3931.00</Value>
			<Value>5663.00</Value>
			<Value>38284.00</Value>
			<Value>19.96</Value>
		</Entry>
		<Entry>
			<Value>Kerala</Value>
			<Value>38863.00</Value>
			<Value>11309.00</Value>
			<Value>0.00</Value>
			<Value>0.00</Value>
			<Value>11309.00</Value>
			<Value>29.10</Value>
		</Entry>
		<Entry>
			<Value>Lakshadweep</Value>
			<Value>0.00</Value>
			<Value>0.00</Value>
			<Value>0.00</Value>
			<Value>0.00</Value>
			<Value>0.00</Value>
			<Value>0.00</Value>
		</Entry>
		<Entry>
			<Value>Madhya Pradesh</Value>
			<Value>308245.00</Value>
			<Value>61886.00</Value>
			<Value>31098.00</Value>
			<Value>1705.00</Value>
			<Value>94689.00</Value>
			<Value>30.72</Value>
		</Entry>
		<Entry>
			<Value>Maharashtra</Value>
			<Value>307713.00</Value>
			<Value>51548.00</Value>
			<Value>6727.00</Value>
			<Value>3082.00</Value>
			<Value>61357.00</Value>
			<Value>19.94</Value>
		</Entry>
		<Entry>
			<Value>Manipur</Value>
			<Value>22327.00</Value>
			<Value>1467.00</Value>
			<Value>4171.00</Value>
			<Value>11780.00</Value>
			<Value>17418.00</Value>
			<Value>78.01</Value>
		</Entry>
		<Entry>
			<Value>Meghalaya</Value>
			<Value>22429.00</Value>
			<Value>1113.00</Value>
			<Value>12.00</Value>
			<Value>8371.00</Value>
			<Value>9496.00</Value>
			<Value>42.34</Value>
		</Entry>
		<Entry>
			<Value>Mizoram</Value>
			<Value>21081.00</Value>
			<Value>7909.00</Value>
			<Value>3568.00</Value>
			<Value>5240.00</Value>
			<Value>16717.00</Value>
			<Value>79.30</Value>
		</Entry>
		<Entry>
			<Value>Nagaland</Value>
			<Value>16579.00</Value>
			<Value>86.00</Value>
			<Value>508.00</Value>
			<Value>8628.00</Value>
			<Value>9222.00</Value>
			<Value>55.62</Value>
		</Entry>
		<Entry>
			<Value>Odisha</Value>
			<Value>155707.00</Value>
			<Value>26329.00</Value>
			<Value>15525.00</Value>
			<Value>16282.00</Value>
			<Value>58136.00</Value>
			<Value>37.34</Value>
		</Entry>
		<Entry>
			<Value>Puducherry</Value>
			<Value>480.00</Value>
			<Value>0.00</Value>
			<Value>2.00</Value>
			<Value>11.00</Value>
			<Value>13.00</Value>
			<Value>2.71</Value>
		</Entry>
		<Entry>
			<Value>Punjab</Value>
			<Value>50362.00</Value>
			<Value>44.00</Value>
			<Value>1137.00</Value>
			<Value>1903.00</Value>
			<Value>3084.00</Value>
			<Value>6.12</Value>
		</Entry>
		<Entry>
			<Value>Rajasthan</Value>
			<Value>342239.00</Value>
			<Value>12475.00</Value>
			<Value>18217.00</Value>
			<Value>2045.00</Value>
			<Value>32737.00</Value>
			<Value>9.57</Value>
		</Entry>
		<Entry>
			<Value>Sikkim</Value>
			<Value>7096.00</Value>
			<Value>5452.00</Value>
			<Value>389.00</Value>
			<Value>0.00</Value>
			<Value>5841.00</Value>
			<Value>82.31</Value>
		</Entry>
		<Entry>
			<Value>Tamil Nadu</Value>
			<Value>130058.00</Value>
			<Value>19388.00</Value>
			<Value>2183.00</Value>
			<Value>1306.00</Value>
			<Value>22877.00</Value>
			<Value>17.59</Value>
		</Entry>
		<Entry>
			<Value>Total</Value>
			<Value>3287263.00</Value>
			<Value>425494.00</Value>
			<Value>214986.00</Value>
			<Value>131341.00</Value>
			<Value>771821.00</Value>
			<Value>23.48</Value>
		</Entry>
		<Entry>
			<Value>Tripura</Value>
			<Value>10486.00</Value>
			<Value>4175.00</Value>
			<Value>2.00</Value>
			<Value>2117.00</Value>
			<Value>6294.00</Value>
			<Value>60.02</Value>
		</Entry>
		<Entry>
			<Value>Uttar Pradesh</Value>
			<Value>240928.00</Value>
			<Value>11660.00</Value>
			<Value>1420.00</Value>
			<Value>3503.00</Value>
			<Value>16583.00</Value>
			<Value>6.88</Value>
		</Entry>
		<Entry>
			<Value>Uttarakhand</Value>
			<Value>53483.00</Value>
			<Value>24643.00</Value>
			<Value>9885.00</Value>
			<Value>123.00</Value>
			<Value>34651.00</Value>
			<Value>64.79</Value>
		</Entry>
		<Entry>
			<Value>West Bengal</Value>
			<Value>88752.00</Value>
			<Value>7054.00</Value>
			<Value>3772.00</Value>
			<Value>1053.00</Value>
			<Value>11879.00</Value>
			<Value>13.38</Value>
		</Entry>
	</Entries>
</Dataset>

=== 52North/worldviz/data/earth/NuclearAccidents.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This sample dataset holds the complete information needed to set-up a visualization for the BO's ENE project. 

Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.

-->
<Dataset version="0.1" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GeneralInformation>
		<Theme>
			<Title>Nuclear accidents</Title>
			<Description>
			This dataset lists those places (not only nuclear power plants) where the most significant nuclear and radiation 
			accidents took place.
			</Description>
		</Theme>
		<Unit/>
		<PublicReference>Wikpedia 2014</PublicReference>
		<MetadataReference>NuclearAccidents_meta.xml</MetadataReference>
	</GeneralInformation>
	<TableStructure>
		<Property dataType="Integer">
			<Title>ID</Title>
			<Description/>
		</Property>
		<Property dataType="String">
			<Title>Longitude,Latitude</Title>
			<Description language="EN">Geographical longitude and latitude as comma-separated string</Description>
			<GeoReference featureType="ENE:Point" externalGeometries="false">
				<CRS>EPSG:4326</CRS>
			</GeoReference>
		</Property>
		<Property dataType="String">
			<Title>Place</Title>
			<Description>Place name in German language</Description>
		</Property>
		<Property dataType="Integer">
			<Title>Year</Title>
			<Description/>
		</Property>
		<Property dataType="Integer">
			<Title>INES scale level</Title>
			<Description/>
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>1</Value>
			<Value>-106.2975,35.8908333</Value>
			<Value>New Mexico</Value>
			<Value>1945</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>10</Value>
			<Value>-84.2502777777777,35.9663611111111</Value>
			<Value>Tennessee</Value>
			<Value>1959</Value>
			<Value>3.50</Value>
		</Entry>
		<Entry>
			<Value>11</Value>
			<Value>-112.057833333333,43.5169166666666</Value>
			<Value>Idaho</Value>
			<Value>1961</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>12</Value>
			<Value>-71.6666666666666,41.3666666666666</Value>
			<Value>Rhode Island</Value>
			<Value>1964</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>13</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1964</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>14</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1965</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>15</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1966</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>16</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1967</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>17</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1968</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>18</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1969</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>19</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1970</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>2</Value>
			<Value>-106.2975,35.8908333</Value>
			<Value>New Mexico</Value>
			<Value>1946</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>20</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1971</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>21</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1972</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>22</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1973</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>23</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1974</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>24</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1975</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>25</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1976</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>26</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1977</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>27</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1978</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>28</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1979</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>29</Value>
			<Value>36.5740555555555,55.0853055555555</Value>
			<Value>Melekess</Value>
			<Value>1966</Value>
			<Value>3.50</Value>
		</Entry>
		<Entry>
			<Value>3</Value>
			<Value>-119.468694444444,46.5296944444444</Value>
			<Value>Washington</Value>
			<Value>1949</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>30</Value>
			<Value>-83.2588055555555,41.9638611111111</Value>
			<Value>Michigan</Value>
			<Value>1966</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>31</Value>
			<Value>6.83888333333333,46.7080611111111</Value>
			<Value>Lucens</Value>
			<Value>1969</Value>
			<Value>4.50</Value>
		</Entry>
		<Entry>
			<Value>32</Value>
			<Value>-105.232277777777,39.8929722222222</Value>
			<Value>Colorado</Value>
			<Value>1969</Value>
			<Value>4.50</Value>
		</Entry>
		<Entry>
			<Value>33</Value>
			<Value>-3.4975,54.4186111111111</Value>
			<Value>Sellafield</Value>
			<Value>1973</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>34</Value>
			<Value>30.0511944444444,59.8521111111111</Value>
			<Value>Leningrad</Value>
			<Value>1974</Value>
			<Value>4.50</Value>
		</Entry>
		<Entry>
			<Value>35</Value>
			<Value>30.0511944444444,59.8521111111111</Value>
			<Value>Leningrad</Value>
			<Value>1975</Value>
			<Value>4.50</Value>
		</Entry>
		<Entry>
			<Value>36</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1977</Value>
			<Value>5.00</Value>
		</Entry>
		<Entry>
			<Value>37</Value>
			<Value>17.6805555555555,48.4944444444444</Value>
			<Value>Jaslovsk√© Bohunice</Value>
			<Value>1977</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>38</Value>
			<Value>61.3166666666666,56.85</Value>
			<Value>Belojarsk</Value>
			<Value>1978</Value>
			<Value>3.50</Value>
		</Entry>
		<Entry>
			<Value>39</Value>
			<Value>-76.725,40.1547222222222</Value>
			<Value>Pennsylvania</Value>
			<Value>1979</Value>
			<Value>5.00</Value>
		</Entry>
		<Entry>
			<Value>4</Value>
			<Value>-77.4486666666666,46.0185555555555</Value>
			<Value>Chalk River</Value>
			<Value>1952</Value>
			<Value>5.00</Value>
		</Entry>
		<Entry>
			<Value>40</Value>
			<Value>4.57861111111111,47.7205555555555</Value>
			<Value>Saint-Laurent</Value>
			<Value>1980</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>41</Value>
			<Value>30.0996944444444,51.3897777777777</Value>
			<Value>Tschernobyl</Value>
			<Value>1982</Value>
			<Value>5.00</Value>
		</Entry>
		<Entry>
			<Value>42</Value>
			<Value>-59.1863888888888,-33.9633333333333</Value>
			<Value>Buenos Aires</Value>
			<Value>1983</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>43</Value>
			<Value>131.9,43.1166666666666</Value>
			<Value>Wladiwostok</Value>
			<Value>1985</Value>
			<Value>5.00</Value>
		</Entry>
		<Entry>
			<Value>44</Value>
			<Value>-95.1318055555555,35.5470277777777</Value>
			<Value>Oklahoma</Value>
			<Value>1986</Value>
			<Value>3.00</Value>
		</Entry>
		<Entry>
			<Value>45</Value>
			<Value>30.0996944444444,51.3897777777777</Value>
			<Value>Tschernobyl</Value>
			<Value>1986</Value>
			<Value>7.00</Value>
		</Entry>
		<Entry>
			<Value>46</Value>
			<Value>84.85,56.6</Value>
			<Value>Sewersk</Value>
			<Value>1993</Value>
			<Value>3.00</Value>
		</Entry>
		<Entry>
			<Value>47</Value>
			<Value>140.606666666666,36.4663888888888</Value>
			<Value>T?kai-mura</Value>
			<Value>1999</Value>
			<Value>3.00</Value>
		</Entry>
		<Entry>
			<Value>48</Value>
			<Value>4.55,50.4666666666666</Value>
			<Value>Fleurus</Value>
			<Value>2006</Value>
			<Value>4.50</Value>
		</Entry>
		<Entry>
			<Value>49</Value>
			<Value>141.0325,37.4166666666666</Value>
			<Value>Fukushima</Value>
			<Value>2011</Value>
			<Value>7.00</Value>
		</Entry>
		<Entry>
			<Value>5</Value>
			<Value>-112.057833333333,43.5169166666666</Value>
			<Value>Idaho</Value>
			<Value>1955</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>6</Value>
			<Value>22.0184722222222,54.4087777777777</Value>
			<Value>Kyschtym</Value>
			<Value>1957</Value>
			<Value>6.00</Value>
		</Entry>
		<Entry>
			<Value>7</Value>
			<Value>-3.4975,54.4186111111111</Value>
			<Value>Sellafield</Value>
			<Value>1957</Value>
			<Value>5.00</Value>
		</Entry>
		<Entry>
			<Value>8</Value>
			<Value>-106.2975,35.8908333333333</Value>
			<Value>New Mexico</Value>
			<Value>1958</Value>
			<Value>4.00</Value>
		</Entry>
		<Entry>
			<Value>9</Value>
			<Value>-118.774055555555,34.2400555555555</Value>
			<Value>Kalifornien</Value>
			<Value>1959</Value>
			<Value>5.50</Value>
		</Entry>
	</Entries>
</Dataset>

=== 52North/worldviz/data/earth/IndiaTreeCover2013.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This sample dataset holds the complete information needed to set-up a visualization for the BO's ENE project. 
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
--><Dataset version="0.1" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GeneralInformation>
		<Theme>
			<Title language="EN">Tree Cover of India States in 2013</Title>
			<Title language="DE">Baumabdeckung der indischen States im Jahr 2013</Title>
			<Description language="DE">
				Die Datei enthält Informationen über die Baumabdeckung der indischen States im Jahr 2013.
			</Description>
		</Theme>
		<Unit/>
		<PublicReference>Dr. Ashok A. Sonkusare</PublicReference>
		<MetadataReference>IndiaTreeCover2013_meta.xml</MetadataReference>
	</GeneralInformation>
	<TableStructure>
		<Property dataType="String" uniqueID="true">
			<Title>State Name</Title>
			<Description>english name of the state</Description>
			<GeoReference featureType="ENE:StateName" externalGeometries="true">
				<CRS>ENE:CountryStates:name</CRS>
			</GeoReference>
		</Property>
		<Property dataType="String">
			<Title>Geographical - Area</Title>
		</Property>
		<Property dataType="String">
			<Title>Tree Cover - Area</Title>
			<Description/>
		</Property>
		<Property dataType="String">
			<Title>Tree Cover - Per cent of GA</Title>
			<Description/>
		</Property>
	</TableStructure>
	<Entries><Entry><Value>Andaman and Nicobar Islands</Value><Value>8,249</Value><Value>41</Value><Value>0.5</Value></Entry><Entry><Value>Andhra Pradesh</Value><Value>2,75,069</Value><Value>7.187</Value><Value>2.61</Value></Entry><Entry><Value>Arunachal Pradesh</Value><Value>83,743</Value><Value>660</Value><Value>0.79</Value></Entry><Entry><Value>Assam</Value><Value>78,438</Value><Value>1.582</Value><Value>2.02</Value></Entry><Entry><Value>Bihar</Value><Value>94,163</Value><Value>2.164</Value><Value>2.3</Value></Entry><Entry><Value>Chandigarh</Value><Value>114</Value><Value>10</Value><Value>8.51</Value></Entry><Entry><Value>Chhattisgarh</Value><Value>1,35,191</Value><Value>3.463</Value><Value>2.56</Value></Entry><Entry><Value>Dadra and Nagar Haveli</Value><Value>491</Value><Value>29</Value><Value>5.95</Value></Entry><Entry><Value>Daman and Diu</Value><Value>112</Value><Value>9</Value><Value>8.46</Value></Entry><Entry><Value>Delhi</Value><Value>1,483</Value><Value>118</Value><Value>7.94</Value></Entry><Entry><Value>Goa</Value><Value>3,702</Value><Value>334</Value><Value>9.03</Value></Entry><Entry><Value>Gujarat</Value><Value>1,96,022</Value><Value>8.358</Value><Value>4.26</Value></Entry><Entry><Value>Haryana</Value><Value>44,212</Value><Value>1.282</Value><Value>2.9</Value></Entry><Entry><Value>Himachal Pradesh</Value><Value>55,673</Value><Value>697</Value><Value>1.25</Value></Entry><Entry><Value>Jammu and Kashmir</Value><Value>2,22,236</Value><Value>7.664</Value><Value>3.45</Value></Entry><Entry><Value>Jharkhand</Value><Value>79,714</Value><Value>2.629</Value><Value>3.3</Value></Entry><Entry><Value>Karnataka</Value><Value>1,91,791</Value><Value>5.920</Value><Value>3.09</Value></Entry><Entry><Value>Kerala</Value><Value>38,863</Value><Value>3.146</Value><Value>8.09</Value></Entry><Entry><Value>Lakshadweep</Value><Value>32</Value><Value>5</Value><Value>16.69</Value></Entry><Entry><Value>Madhya Pradesh</Value><Value>3,08,245</Value><Value>7.087</Value><Value>2.3</Value></Entry><Entry><Value>Maharashtra</Value><Value>3,07,713</Value><Value>9.142</Value><Value>2.97</Value></Entry><Entry><Value>Manipur</Value><Value>22,327</Value><Value>224</Value><Value>1</Value></Entry><Entry><Value>Meghalaya</Value><Value>22,429</Value><Value>668</Value><Value>2.98</Value></Entry><Entry><Value>Mizoram</Value><Value>21,081</Value><Value>223</Value><Value>1.06</Value></Entry><Entry><Value>Nagaland</Value><Value>16,579</Value><Value>372</Value><Value>2.24</Value></Entry><Entry><Value>Odisha</Value><Value>1,55,707</Value><Value>4.013</Value><Value>2.58</Value></Entry><Entry><Value>Puducherry</Value><Value>480</Value><Value>29</Value><Value>6.07</Value></Entry><Entry><Value>Punjab</Value><Value>50,362</Value><Value>1.499</Value><Value>2.98</Value></Entry><Entry><Value>Rajasthan</Value><Value>3,42,239</Value><Value>7.860</Value><Value>2.3</Value></Entry><Entry><Value>Sikkim</Value><Value>7,096</Value><Value>31</Value><Value>0.44</Value></Entry><Entry><Value>TOTAL</Value><Value>32,87,263</Value><Value>91.266</Value><Value>2.78</Value></Entry><Entry><Value>Tamil Nadu</Value><Value>1,30,058</Value><Value>4.866</Value><Value>3.74</Value></Entry><Entry><Value>Tripura</Value><Value>10,486</Value><Value>213</Value><Value>2.03</Value></Entry><Entry><Value>Uttar Pradesh</Value><Value>2,40,928</Value><Value>6.895</Value><Value>2.86</Value></Entry><Entry><Value>Uttarakhand</Value><Value>53,483</Value><Value>703</Value><Value>1.32</Value></Entry><Entry><Value>West Bengal</Value><Value>88,752</Value><Value>2.144</Value><Value>2.42</Value></Entry></Entries>
</Dataset>
