=== 52North/worldviz/data/earth/xsd/Dataset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
XML Schema Definition (XSD) for datasets that will be processed in the context of the WorldViz project. 
Authors: Benno Schmidt, Christian Danowski, Department of Geodesy, Bochum University of Applied Sciences.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Dataset">
		<xs:annotation>
			<xs:documentation>
			This file holds the complete information needed to set-up a visualization (e.g., inside the Erlebnisraum).
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="GeneralInformation">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Theme">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Title" type="Title"/>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Description" type="Description"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Unit">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Title" type="Title"/>
										<xs:element maxOccurs="1" minOccurs="0" name="Code" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="PublicReference" type="xs:string"/>
							<xs:element name="MetadataReference" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="TableStructure">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="Property">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Title" type="Title"/>
										<xs:element maxOccurs="1" minOccurs="0" name="TimeReference">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="begin" type="xs:date"/>
													<xs:element name="end" type="xs:date"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Description" type="Description"/>
										<xs:element minOccurs="0" name="GeoReference">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="CRS" type="crs"/>
												</xs:sequence>
												<xs:attribute name="featureType" type="xs:string"/>
												<xs:attribute name="externalGeometries" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="dataType" type="xs:string" use="optional"/>
									<xs:attribute name="uniqueID" type="xs:boolean" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Entries">
					<xs:annotation>
						<xs:documentation>usw.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="Entry">
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Value" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:float"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Description">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="languageCode"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="Title">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="languageCode"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="languageCode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EN"/>
			<xs:enumeration value="DE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="crs">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ENE:CountriesWorldwide:iso3166-2"/>
			<xs:enumeration value="EPSG:4326"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== 52North/worldviz/data/earth/EarthTimeLapseViewfromSpace.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This sample dataset holds the complete information needed to set-up a visualization for the BO's ENE project. 
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<Dataset version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd">
	<GeneralInformation>
		<Theme>
			<Title language="EN">Earth Time Lapse View from Space</Title>
			<Title language="DE">Satellitenbildaufnahmen der Erde</Title>
			<Description>
 (Tzhe following text passages are taken from the original metadata-file of the video, link: https://archive.org/download/EarthTimeLapseViewfromSpace/EarthTimeLapseViewfromSpace_meta.xml)
			Time lapse sequences of photographs taken by Ron Garan
fragileoasis.org/âbloggernauts/âAstro_Ron and the crew of expedition
28 &amp; 29 onboard the International Space Station from August to October,
2011, who to my knowledge shot these pictures at an altitude of around
350 km with a high ISO HD Camera developed by NHK Japan,
nicknamed the SS-HDTV camera. All credit goes to them.
I intend to upload a FullHD-version presently.

HD, refurbished, smoothed, retimed, denoised, deflickered, cut, etc.
All in all I tried to keep the looks of the material as original as possible,
avoided adjusting the colors and the like, since in my opinion the original
footage itself already has an almost surreal and aestethical visual nature.

Music: Jan Jelinek | Do Dekor, faitiche back2001
w+p by Jan Jelinek, published by Betke Edition
janjelinek.com | faitiche.de

Image Courtesy of the Image Science &amp; Analysis Laboratory,
NASA Johnson Space Center, The Gateway to Astronaut Photography of Earth
eol.jsc.nasa.gov

Editing: Michael KÃ¶nig | koenigm.com

Shooting locations in order of appearance:

1. Aurora Borealis Pass over the United States at Night
2. Aurora Borealis and eastern United States at Night
3. Aurora Australis from Madagascar to southwest of Australia
4. Aurora Australis south of Australia
5. Northwest coast of United States to Central South America at Night
6. Aurora Australis from the Southern to the Northern Pacific Ocean
7. Halfway around the World
8. Night Pass over Central Africa and the Middle East
9. Evening Pass over the Sahara Desert and the Middle East
10. Pass over Canada and Central United States at Night
11. Pass over Southern California to Hudson Bay
12. Islands in the Philippine Sea at Night
13. Pass over Eastern Asia to Philippine Sea and Guam
14. Views of the Mideast at Night
15. Night Pass over Mediterranean Sea
16. Aurora Borealis and the United States at Night
17. Aurora Australis over Indian Ocean
18. Eastern Europe to Southeastern Asia at Night
			</Description>
		</Theme>
		<Unit />
		<PublicReference>https://archive.org/details/EarthTimeLapseViewfromSpace, Jeff Kaplan</PublicReference>
		<MetadataReference>EarthTimeLapseViewfromSpace_meta.xml</MetadataReference>
	</GeneralInformation>
	<TableStructure>
		<Property dataType="">
			<Title>Spatial extent</Title>
			<Description />
			<GeoReference featureType="ENE:Video" externalGeometries="false">
				<CRS>EPSG:4326</CRS>
			</GeoReference>
		</Property>
		<Property dataType="String">
			<Title>File name</Title>
		</Property>
		<Property dataType="String">
			<Title>Video size</Title>
			<Description>Viedo size in MB</Description>
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>-180,-90,180,90</Value>
			<Value>https://archive.org/download/EarthTimeLapseViewfromSpace/EarthTimeLapseViewfromSpace.mp4</Value>
			<Value>29.7</Value>
		</Entry>
	</Entries>
</Dataset>

=== 52North/worldviz/data/earth/IndiaStates_simplifiedBorders.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This sample dataset holds the complete information needed to set-up a visualization for the BO's ENE project. 
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<Dataset version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd">
	<GeneralInformation>
		<Theme>
			<Title language="EN">India States as shape-file</Title>
			<Title language="DE">Shape mit indischen Staatsgrenzen (mit deutschen Bundesl√§ndern zu vergleichen)</Title>
			<Description language="DE">
				Dieses Dokument verweist auf die Quelldatei mit den vereinfachten Geometrien der indischen Staatsgrenzen (ESRI-Shape-Format). 
				In der Shape-Datei sind die Namen der States in der Spalte "NAME" eingetragen, sodass ueber die "IndiaStateNames.xml"
				eine Georeferenzierung laenderbezogener statistischer Daten moeglich wird.
			</Description>
		</Theme>
		<Unit />
		<PublicReference>Devdatta Tengshe</PublicReference>
		<MetadataReference>IndiaStates_simplifiedBorders_meta.xml</MetadataReference>
	</GeneralInformation>
	<TableStructure>
		<Property dataType="String">
			<Title>Shape file name</Title>
			<GeoReference featureType="ENE:EsriShape">
				<CRS>EPSG:4326</CRS>
			</GeoReference>
		</Property>
		<Property dataType="String">
			<Title>Database file name</Title>
		</Property>
		<Property dataType="String">
			<Title>Spatial extent</Title>
			<Description />
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>India_States/IndiaAdmin2.shp</Value>
			<Value>India_States/IndiaAdmin2.dbf</Value>
			<Value>68.0,6.8,97.4,37.1</Value>
		</Entry>
	</Entries>
</Dataset>

=== 52North/worldviz/data/earth/EarthAtNight.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This sample dataset holds the complete information needed to set-up a visualization for the BO's ENE project. 
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<Dataset version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd">
	<GeneralInformation>
		<Theme>
			<Title language="EN">Nocturnal lighting situation</Title>
			<Title language="DE">Naechtliche Beleuchtungsituation der Erde</Title>
			<Description>
			This dataset illustrates the nocturnal lighting-situation. This global view of Earth's city lights is a composite 
			assembled from data acquired by the Suomi NPP satellite. The data was acquired over nine days in April 2012 
			and 13 days in October 2012. It took 312 orbits to get a clear shot of every parcel of Earth's land surface and islands. 
			This new data was then mapped over existing Blue Marble imagery of Earth to provide a realistic view of the planet.
			</Description>
		</Theme>
		<Unit />
		<PublicReference>NASA Earth Observatory/NOAA NGDC 2012</PublicReference>
		<MetadataReference>EarthAtNight_meta.xml</MetadataReference>
	</GeneralInformation>
	<TableStructure>
		<Property dataType="">
			<Title>Spatial extent</Title>
			<Description />
			<GeoReference featureType="ENE:Bitmap" externalGeometries="false">
				<CRS>EPSG:4326</CRS>
			</GeoReference>
		</Property>
		<Property dataType="String">
			<Title>File name</Title>
		</Property>
		<Property dataType="String">
			<Title>Image size</Title>
			<Description>Image size in pixels</Description>
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>-180,-90,180,90</Value>
			<Value>EarthAtNight.jpg</Value>
			<Value>3600x1800</Value>
		</Entry>
	</Entries>
</Dataset>

=== 52North/worldviz/data/earth/ElectricityConsumption.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This sample dataset holds the complete information needed to set-up a visualization for the BO's ENE project. 
Authors: Christian Danowski, Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<Dataset version="0.1" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GeneralInformation>
		<Theme>
			<Title language="EN">Electricity Consumption</Title><!-- Titel bezogen auf die Sprache: Englisch-->
			<Title language="DE">Stromverbrauch</Title><!-- Titel bezogen auf die Sprache: Deutsch-->
			<Description language="EN">This dataset gives the electricity comsumption for the years 2000, 2005-2009 in terrawatts per hours for the World's countries.</Description><!-- Erklärung auf Englisch-->
			<Description language="DE">Dieser Datensatz enthält staatenweise den Stromverbrauch in Terawattstunden für die Jahre 2000, 2005-2009.</Description><!-- Erklärung auf Deutsch-->
		</Theme>
		<Unit>
			<Title>Terawatt hours per year</Title><!-- Einheiten auf welche sich die gegebenen Daten beziehen: Englisch-->
			<Code>TWh/a</Code><!-- Einheiten Kodiert-->
		</Unit>
		<PublicReference>Wikipedia</PublicReference>
		<MetadataReference>ElectricityConsumption_meta.xml</MetadataReference><!-- Referenz der Metadatendatei-->
	</GeneralInformation>
	<TableStructure>
		<Property dataType="ENE:iso3166-2" uniqueID="true"><!-- Hier verwendete Kodierliste bezüglich der Länderkürzel-->
			<Title>Country code</Title><!-- Titel-->
			<Description>Country code ISO 3166-2</Description><!-- For geo-referenced 
properties, a GeoReference element should be present: -->
			<GeoReference featureType="ENE:CountryCode" externalGeometries="true">
				<CRS>ENE:CountriesWorldwide:iso3166-2</CRS>
			</GeoReference>
		</Property>
		<Property dataType="Float">
			<Title>2000</Title><!-- For time-referenced 
properties, a TimeReference element should be present: -->
			<TimeReference>
				<begin>2000-01-01+01:00</begin>
				<end>2000-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2005</Title>
			<TimeReference>
				<begin>2005-01-01+01:00</begin>
				<end>2005-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2006</Title>
			<TimeReference>
				<begin>2006-01-01+01:00</begin>
				<end>2006-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2007</Title>
			<TimeReference>
				<begin>2007-01-01+01:00</begin>
				<end>2007-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2008</Title>
			<TimeReference>
				<begin>2008-01-01+01:00</begin>
				<end>2008-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
		<Property dataType="Float">
			<Title>2009</Title>
			<TimeReference>
				<begin>2009-01-01+01:00</begin>
				<end>2009-12-31+01:00</end>
			</TimeReference>
			<Description/>
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>AU</Value>
			<Value>182.9</Value>
			<Value>212.4</Value>
			<Value>214.2</Value>
			<Value>220.2</Value>
			<Value>225.3</Value>
			<Value>228.8</Value>
		</Entry>
		<Entry>
			<Value>BR</Value>
			<Value>321.6</Value>
			<Value>368.8</Value>
			<Value>383.2</Value>
			<Value>405.1</Value>
			<Value>420.0</Value>
			<Value>418.0</Value>
		</Entry>
		<Entry>
			<Value>CA</Value>
			<Value>504.8</Value>
			<Value>541.3</Value>
			<Value>528.7</Value>
			<Value>536.0</Value>
			<Value>528.5</Value>
			<Value>504.8</Value>
		</Entry>
		<Entry>
			<Value>CN</Value>
			<Value>1177.9</Value>
			<Value>2195.1</Value>
			<Value>2528.9</Value>
			<Value>2833.2</Value>
			<Value>3018.2</Value>
			<Value>3253.2</Value>
		</Entry>
		<Entry>
			<Value>DE</Value>
			<Value>503.2</Value>
			<Value>543.4</Value>
			<Value>547.4</Value>
			<Value>547.3</Value>
			<Value>544.5</Value>
			<Value>509.5</Value>
		</Entry>
		<Entry>
			<Value>ES</Value>
			<Value>193.6</Value>
			<Value>244.4</Value>
			<Value>261.0</Value>
			<Value>263.8</Value>
			<Value>270.7</Value>
			<Value>256.6</Value>
		</Entry>
		<Entry>
			<Value>FR</Value>
			<Value>409.8</Value>
			<Value>449.9</Value>
			<Value>445.2</Value>
			<Value>447.2</Value>
			<Value>460.2</Value>
			<Value>451.4</Value>
		</Entry>
		<Entry>
			<Value>GB</Value>
			<Value>335.4</Value>
			<Value>352.5</Value>
			<Value>349.9</Value>
			<Value>347.6</Value>
			<Value>344.3</Value>
			<Value>325.8</Value>
		</Entry>
		<Entry>
			<Value>IN</Value>
			<Value>375.4</Value>
			<Value>483.3</Value>
			<Value>531.5</Value>
			<Value>590.6</Value>
			<Value>626.5</Value>
			<Value>637.6</Value>
		</Entry>
		<Entry>
			<Value>IR</Value>
			<Value>92.9</Value>
			<Value>135.4</Value>
			<Value>148.8</Value>
			<Value>156.6</Value>
			<Value>166.2</Value>
			<Value>173.1</Value>
		</Entry>
		<Entry>
			<Value>IT</Value>
			<Value>278.7</Value>
			<Value>307.1</Value>
			<Value>314.0</Value>
			<Value>314.9</Value>
			<Value>314.6</Value>
			<Value>296.3</Value>
		</Entry>
		<Entry>
			<Value>JP</Value>
			<Value>940.7</Value>
			<Value>977.7</Value>
			<Value>983.9</Value>
			<Value>1009.0</Value>
			<Value>966.4</Value>
			<Value>934.3</Value>
		</Entry>
		<Entry>
			<Value>KR</Value>
			<Value>236.2</Value>
			<Value>352.3</Value>
			<Value>364.9</Value>
			<Value>386.2</Value>
			<Value>402.0</Value>
			<Value>408.5</Value>
		</Entry>
		<Entry>
			<Value>MX</Value>
			<Value>159.9</Value>
			<Value>192.2</Value>
			<Value>196.4</Value>
			<Value>202.1</Value>
			<Value>206.1</Value>
			<Value>203.7</Value>
		</Entry>
		<Entry>
			<Value>RU</Value>
			<Value>715.5</Value>
			<Value>776.8</Value>
			<Value>816.0</Value>
			<Value>844.4</Value>
			<Value>857.6</Value>
			<Value>808.0</Value>
		</Entry>
		<Entry>
			<Value>SA</Value>
			<Value>109.5</Value>
			<Value>147.0</Value>
			<Value>156.8</Value>
			<Value>163.4</Value>
			<Value>174.2</Value>
			<Value>186.1</Value>
		</Entry>
		<Entry>
			<Value>TR</Value>
			<Value>98.6</Value>
			<Value>129.0</Value>
			<Value>141.5</Value>
			<Value>153.7</Value>
			<Value>160.4</Value>
			<Value>155.2</Value>
		</Entry>
		<Entry>
			<Value>TW</Value>
			<Value>163.4</Value>
			<Value>199.7</Value>
			<Value>205.5</Value>
			<Value>215.3</Value>
			<Value>212.7</Value>
			<Value>203.8</Value>
		</Entry>
		<Entry>
			<Value>US</Value>
			<Value>3592.4</Value>
			<Value>3811.0</Value>
			<Value>3816.8</Value>
			<Value>3890.2</Value>
			<Value>3865.2</Value>
			<Value>3723.8</Value>
		</Entry>
		<Entry>
			<Value>ZA</Value>
			<Value>180.1</Value>
			<Value>205.0</Value>
			<Value>210.6</Value>
			<Value>219.6</Value>
			<Value>212.2</Value>
			<Value>206.1</Value>
		</Entry>
	</Entries>
</Dataset>

=== 52North/worldviz/data/earth/color_etopo1_ice_low.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This sample dataset holds the complete information needed to set-up a visualization for the BO's ENE project. 
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<Dataset version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd">
	<GeneralInformation>
		<Theme>
			<Title language="EN">Global Relief Model of the earth</Title>
			<Title language="DE">Globals Relief-Modell der Erde</Title>
			<Description>
			This dataset illustrates the global relief model of the earth that integrates topography and bathymetry.
			</Description>
		</Theme>
		<Unit />
		<PublicReference>NOAA NGDC 2012</PublicReference>
		<MetadataReference>color_etopo1_ice_low_meta.xml</MetadataReference>
	</GeneralInformation>
	<TableStructure>
		<Property dataType="">
			<Title>Spatial extent</Title>
			<Description />
			<GeoReference featureType="ENE:Bitmap" externalGeometries="false">
				<CRS>EPSG:4326</CRS>
			</GeoReference>
		</Property>
		<Property dataType="String">
			<Title>File name</Title>
		</Property>
		<Property dataType="String">
			<Title>Image size</Title>
			<Description>Image size in pixels</Description>
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>-180,-90,180,90</Value>
			<Value>color_etopo1_ice_low.jpg</Value>
			<Value>5400x2700</Value>
		</Entry>
	</Entries>
</Dataset>

=== 52North/worldviz/data/Flows_of_trade.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
WorldViz dataset description. 
Note: This dataset holds information needed to set-up proper visualizations inside WorldViz. 
Author: Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<Dataset version="0.1" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GeneralInformation>
		<Theme>
			<Title language="EN">Global flows of trade</Title>
			<Title language="DE">Welthandelsströme</Title>
			<Description>
			This dataset gives the flows of trade (volumes greater than 30 billion US-$ only, for 2004) in Pajek format. 
			Internal trades (volumes in billion US-$, 2004) are given by loops, i.e. arcs with from-vertex = to-vertex. 
			Markets are given as vertices with lon/lat coordinates.
			</Description>
		</Theme>
		<Unit>Billion US-$</Unit>
		<PublicReference>Dr. Peter Güttler, Berlin</PublicReference>
		<MetadataReference>Flows_of_trade_meta.xml</MetadataReference>
	</GeneralInformation>
	<TableStructure>
		<Property dataType="">
			<Title>Spatial extent</Title>
			<Description/>
			<GeoReference featureType="Wviz:Pajek" externalGeometries="false">
				<CRS>EPSG:4326</CRS>
			</GeoReference>
		</Property>
		<Property dataType="String">
			<Title>File name</Title>
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>-180,-90,180,90</Value>
			<Value>Flows_of_trad.net</Value>
		</Entry>
	</Entries>
</Dataset>

=== 52North/worldviz/data/earth/IndiaStateNames.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Country-code information for the BO's ENE project. 
Authors: Christian Danowski, Benno Schmidt, Department of Geodesy, Bochum University of Applied Sciences.
-->
<Dataset version="0.1" xsi:noNamespaceSchemaLocation="xsd/Dataset.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GeneralInformation>
		<Theme>
			<Title>India State Names</Title>
			<Description>
			 This dataset gives some India state names.
			 </Description>
		</Theme>
		<Unit/>
		<PublicReference/>
		<MetadataReference>IndiaStateNames_meta.xml</MetadataReference>
	</GeneralInformation>
	<TableStructure>
		<Property dataType="String" uniqueID="true">
			<Title>State Name</Title>
			<Description>english name of the state</Description>
			<GeoReference featureType="ENE:StateName" externalGeometries="true">
				<CRS>ENE:CountryStates:name</CRS>
			</GeoReference>
		</Property>
	</TableStructure>
	<Entries>
		<Entry>
			<Value>Andaman and Nicobar Island</Value>
		</Entry>
		<Entry>
			<Value>Andhra Pradesh</Value>
		</Entry>
		<Entry>
			<Value>Arunachal Pradesh</Value>
		</Entry>
		<Entry>
			<Value>Assam</Value>
		</Entry>
		<Entry>
			<Value>Bihar</Value>
		</Entry>
		<Entry>
			<Value>Chandigarh</Value>
		</Entry>
		<Entry>
			<Value>Chhattisgarh</Value>
		</Entry>
		<Entry>
			<Value>Dadra and Nagar Haveli</Value>
		</Entry>
		<Entry>
			<Value>Daman and Diu</Value>
		</Entry>
		<Entry>
			<Value>Delhi</Value>
		</Entry>
		<Entry>
			<Value>Goa</Value>
		</Entry>
		<Entry>
			<Value>Gujarat</Value>
		</Entry>
		<Entry>
			<Value>Haryana</Value>
		</Entry>
		<Entry>
			<Value>Himachal Pradesh</Value>
		</Entry>
		<Entry>
			<Value>Jammu and Kashmir</Value>
		</Entry>
		<Entry>
			<Value>Jharkhand</Value>
		</Entry>
		<Entry>
			<Value>Karnataka</Value>
		</Entry>
		<Entry>
			<Value>Kerala</Value>
		</Entry>
		<Entry>
			<Value>Lakshadweep</Value>
		</Entry>
		<Entry>
			<Value>Madhya Pradesh</Value>
		</Entry>
		<Entry>
			<Value>Maharashtra</Value>
		</Entry>
		<Entry>
			<Value>Manipur</Value>
		</Entry>
		<Entry>
			<Value>Meghalaya</Value>
		</Entry>
		<Entry>
			<Value>Mizoram</Value>
		</Entry>
		<Entry>
			<Value>Nagaland</Value>
		</Entry>
		<Entry>
			<Value>Odisha</Value>
		</Entry>
		<Entry>
			<Value>Puducherry</Value>
		</Entry>
		<Entry>
			<Value>Punjab</Value>
		</Entry>
		<Entry>
			<Value>Rajasthan</Value>
		</Entry>
		<Entry>
			<Value>Sikkim</Value>
		</Entry>
		<Entry>
			<Value>Tamil Nadu</Value>
		</Entry>
		<Entry>
			<Value>Telangana</Value>
		</Entry>
		<Entry>
			<Value>Tripura</Value>
		</Entry>
		<Entry>
			<Value>Uttar Pradesh</Value>
		</Entry>
		<Entry>
			<Value>Uttarakhand</Value>
		</Entry>
		<Entry>
			<Value>West Bengal</Value>
		</Entry>
	</Entries>
</Dataset>
